### ISSUE TITLE
Feature Request: Craftconomy Multiple Currencies

### ISSUE THREAD

**Issue by JericM** [MilkBowl/Vault#404]
I don't know if this is a Craftconomy thing or a vault thing, so I will post it in both plugins' pages. Craftconomy has a unique feature that allows multiple currencies, but currently, Vault will only pull from the server's "default" currency, rendering the other currencies null. What I think Vault SHOULD do is hook better into Craftconomy and interpret other currencies as valid. 
I really don't know how it all works, but let me know if I'm way off base posting this here. Thanks!

**Comment by AvatarAcid** [comment]
I have experienced the same as above. I was able to actually create the currencies and assign a different currency to a different world, but when using plugins like signshop, it wouldn't pull the money out of anything but the default balance.

I wanted to have two worlds with two unique balance books and currencies where you could only access one of them from the corresponding world. This would be a great feature to have.
