### ISSUE TITLE
Vault 

### ISSUE THREAD

**Issue by FearlessFrost** [MilkBowl/Vault#590]
As a foreword, I'm not even sure if this is a problem with vault, but I figured I'd start here and see if I could get any potential answers to the issue I'm having.

Some of the plugins I'm using can't find a vault supported economy plugin, according to the start up log. I'm using Spigot Essentials (Essentials vTeamcity) as it's the only 1.8 essentials out there. 
These two output the most information about not finding an economy plugin:
GriefPrevention Start-up: http://pastebin.com/Af9iduut
PrimeShop: http://pastebin.com/iT9gsq32

Full start-up log: http://pastebin.com/5wpXBMZr

I tried switching to CraftConomy to see if it was an Essentials issue, but I got the same results as above. I've also tried re-installing all affected plugins and installing them one at a time. 

Thanks in advance for any help/answers!

**Comment by Sleaker** [comment]
Looks like an issue with griefprevention.  Vault is clearly indicating the hooks are available. you can run /vault-info to verify in-game that vault sees connectors.

**Comment by FearlessFrost** [comment]
Okay, I'll ask around elsewhere. Thank you!
