### ISSUE TITLE
Vault 1.5.2 Breaking other plugins

### ISSUE THREAD

**Issue by krustymk** [MilkBowl/Vault#591]
http://pastebin.com/0xfwfUE4

**Comment by Sleaker** [comment]
This is not a Vault issue. This means you're either not running the correct CC3 version, or there is a problem with your JVM finding classes.

**Comment by krustymk** [comment]
The latest CC3 REQUIRES 1.5.2! 
http://dev.bukkit.org/bukkit-plugins/craftconomy/files/27-3-2/ 

Maybe my JVM isnt finding classes properly, I have 24 plugins and 1.5.2 has been the only issue and returning to 1.5.0  cured them. How would i test?
