### ISSUE TITLE
vault 1.5.2 issue (required for craftconomy 3.2)

### ISSUE THREAD

**Issue by krustymk** [MilkBowl/Vault#592]
My hosts reply to the errors generated by the plugin.

http://pastebin.com/0xfwfUE4

Hi krustymk,
This sounds like an issue with calling something that does not exist not with the Java Virtual Machine, this is simply stating that no method exists.  The problem isn't our JVM but that the correct classes haven't been called or loaded.

**Comment by krustymk** [comment]
That was the response from my host.
Craftconomy author says we must use 1.5.2

**Comment by Sleaker** [comment]
I need more information on what versions you're using and where you obtained them.

**Comment by krustymk** [comment]
http://pastebin.com/vNhjpd0b Craftconomy3.2 Vault1.5.2 working

http://pastebin.com/CK94iuve Stats2.0.1 Vault1.5.2 working

http://pastebin.com/t2cyJBhh Vault1.5.2 Craftconomy3.2 Stats2.0.1 errors

Hopefully this should help answer your questions? Ive made these available to both of the authors also... Way out of my area of expertise

**Comment by krustymk** [comment]
From my host

Hi krustymk,

I just ran a test suite against the JRE and everything worked perfectly. 
Let us know, from what I see and tested JVM/JRE is working correctly on the machine.

**Comment by Sleaker** [comment]
nullPointerError is much different than classnotfound.
