### ISSUE TITLE
Not hooking to the new bPermissions Version 3.0

### ISSUE THREAD

**Issue by 2008Choco** [MilkBowl/Vault#593]
Describe to us the issue that you're having:
Because of the new update, Vault doesn't seem to recognize the new version of bPermissions. I don't know if bPermissions has to update, or if Vault has to modify the code so that it hooks with bPermissions. I thought I'd put in a ticket here, and in bPermissions just in case.

Which steps will reproduce this problem?:
1) Download Vault version 1.5.2 for 1.8 and install it on your server
2) Download bPermissions version 3.0 for 1.8.1 and install it on your server
3) Run your server
....

Do you have an error log of what happened?
There are no logs. When Vault loads, it doesn't even notice that bPermissions V3.0 is even there

Which version of Vault are you using?: (Please don't say "latest"!!!)
Version 1.5.2, Minecraft 1.8 / 1.8.1

Which version of CraftBukkit?
craftbukkit-1.8-R0.1-SNAPSHOT

Which OS?
Microsoft, Windows 8

Any other information we may need (plugins, configs, etc):
I didn't mess with any of the configurations for either of the plugins because they wouldn't hook. Why would I do that ;3
Also, I use bPermissions and Vault in the 1.7 version of my server perfectly fine, and they hook okay. Same plugins in 1.8 (of course some are updated) but in 1.8 it just doesn't hook.

**Comment by Sleaker** [comment]
the official developer of bpermissions indicates that 3.0 is not ready for production.  If 3.0 does become official the bPermissions team will need to add in their own Vault hooks as I am no longer adding in new connectors and maintaining them myself.  it is up to permission plugin developers to properly distribute a working connector for Vault.
