### ISSUE TITLE
Vault-Convert Locks server

### ISSUE THREAD

**Issue by Trikolon** [MilkBowl/Vault#596]
I'm currently trying to convert my Boseconomy data to EssentialsEconomy. The command seems to lock up the server though which causes the crash-detection to trigger and restart the server. Could you make the conversion run in a seperate thread?

**Comment by Sleaker** [comment]
I'm not familiar with crash detection. is this something new, or an extra piece of software you're using?

**Comment by veteranmina** [comment]
Sounds like it could be watchdog that has caused this to trigger. Putting vault in another thread could bypass this if vault was to trigger a crash.

**Comment by Sleaker** [comment]
Closing this as the documentation even states that convert should be left alone to run by itself.

**Comment by veteranmina** [comment]
Please re-open this issue, as it was left alone to run, but a process called watchdog senses a "crash" and closes the thread. As I stated, it would be handy if this could be put in another thread so to keep watchdog from triggering a close of the thread. This is not the scenario that is stated in documentation.

**Comment by Sleaker** [comment]
@veteranmina - vault-convert command is expressedly given as-is, and may not work for all situations. watchdog can be manipulated by changing the max-tick-time, conversions should never be run on live servers.
