### ISSUE TITLE
Charge for Landclaim

### ISSUE THREAD

**Issue by bradleyd887** [MilkBowl/Vault#597]
I'm not sure I will find help here as I'm sure this belongs on the wglandclaim page (I haven't gotten a response there) but it lists this as a dependency so I figured I would try here. I'm running spigot 1.8, essentials (world guard land claim and vault plugins). I believe I have all of the perms set up, and players may claim region if they have the money but the plugin doesn't actually take the money when the region is claimed. So it checks and denies if they don't have the money, and if they do it allows the region creation but doesn't charge. Is this a vault issue or landclaim? I can attach configs asap just wanted to check before I wasted anyone's time.

**Comment by Sleaker** [comment]
Vault only provides the interface for plugins to do things with economy plugins.  I suggest filing a bug report with the landclaim plugin so they can either help you get it setup, or figure out what the issue is.
