### ISSUE TITLE
ColoredGroups support

### ISSUE THREAD

**Issue by nsporillo** [MilkBowl/Vault#599]
Vault support for the chat plugin: http://dev.bukkit.org/bukkit-plugins/coloredgroups/

I'm the author, making this issue so that when (if) I make a PR I can reference this issue id.

If I don't get around to making a PR, it'd still be beneficial to the project to add support as ColoredGroups has over 20k downloads and is still supported.

**Comment by Sleaker** [comment]
Connector's are no longer added into vault directly, you can add a connector into your project directly though.
