### ISSUE TITLE
Request: Support ico 5.01 again.

### ISSUE THREAD

**Issue by LlmDl** [MilkBowl/Vault#603]
Hi, 

I'm requesting that support for ico 5.01 be added back in. The plugin is maintained by ElgarL and still works fine after all these years. It doesn't receive frequent updates as it does not require them, it is a rock-solid economy plugin.

**Comment by LlmDl** [comment]
http://i.imgur.com/iiBRqOL.gif

**Comment by Sleaker** [comment]
If it's being maintained then the connector can be implemented in the maintained version.
