### ISSUE TITLE
Vault hooks into both Essentials and CraftConomy3

### ISSUE THREAD

**Issue by Rocologo** [MilkBowl/Vault#608]
Vault Hooks into both CraftConomy and Essentials, and this means that i get two different balances, depending on if i use /balance (Essentials) or /money (craftconomy) if i spend money with they are withdrawn from essentials economy and not in craftconomy as intended?

**Comment by Sleaker** [comment]
depends on priority of the registrations. Whichever has a higher priority will get utilized.
