### ISSUE TITLE
Vault no longer works in Spigot 1.8.7

### ISSUE THREAD

**Issue by datsme** [MilkBowl/Vault#611]

**Comment by Sleaker** [comment]
Please provide error logs with what your server is throwing so I can investigate the issue.

**Comment by datsme** [comment]
Actually I only used Vault because it was required by WoldEdit but with their new version Vault is no longer required so I just removed Vault.

But, thank you for responding.

**Comment by Noket** [comment]
it still helps the developer if you provide error logs, that way other
people benefit from your troubleshooting

**Comment by Sleaker** [comment]
Verified with others that Vault works just fine with Spigot 1.8.7. Not sure what issue you were having but its not a versioning issue.
