### ISSUE TITLE
Custom economy plugin

### ISSUE THREAD

**Issue by 1461748123** [MilkBowl/Vault#612]
Hi!
I'm new in Ant and Maven so I got no idea how to build Vault.
I tried to pull Vault down and edit it directly but it doesn't work(of course).
Can you please help? Thanks!

**Comment by Sleaker** [comment]
You don't edit Vault when you want to implement your own economy.  You add it as a library and build against it.  In your economy you just implement the Economy interface in Vault and provide the methods with a similar style as the already created connectors.  To make sure your connector loads up properly you should set the connector to load on startup.  If you need help doing this spigot/bukkit forums have multiple references and can provide help for doing this.

**Comment by 1461748123** [comment]
Can you please give an example? I search over the net but doesn't found much useful information.
Most of them are how to use vault to control economy plugin instead of build an economy plugin.

**Comment by Sleaker** [comment]
I don't remember which plugins have them, there have been multiple people on here that have done the same thing as you though.  Check through the past issues.
