### ISSUE TITLE
Vault Issue

### ISSUE THREAD

**Issue by MarkElf** [MilkBowl/Vault#614]
Hey, I'm having an issue with Vault where it doesn't seem to load while the server thinks it does as far as I understand. I have vault.jar in the plugins folder and when using /plugman load vault it states "That the file is not a valid plugin". It doesn't load when the server reboots either.I had someone else with a bit of developer knowledge and pointed out this: http://pastebin.com/dMHWZJQM. If you need anymore information let me know.

**Comment by agalitsas** [comment]
i have the same problem... i use spigot 1.8.7 with java 1.8..
with java 1.7 loads normal... but i need to use java 1.8..

**Comment by Sleaker** [comment]
@MarkElf - that error is actually stating the plugin is already loaded, not that it's invalid.  
@agalitsas - We have Vault running with Spigot 1.8.7 and both Java7 and java8.

I need an actual message stating what the error is when the server starts with Vault, if there is no error and Vault is logging to the command line then it is functioning.  What functionality that Vault provides are you not seeing? Can you use the /vault-info command? etc.

**Comment by MarkElf** [comment]
Right, I meant that,  I just couldn't phrase it properly but the issue is that other plugins that I'm using don't detect vault being loaded while it is. http://pastebin.com/Y22tgggW

**Comment by Sleaker** [comment]
@MarkElf - you're not actually showing the portion of the log where Vault is loading, nor are you showing what happens when you try to use the vault command /vault-info.  You also did not answer where you downloaded it from. It would also be helpful if you posted what version you were using (should be able to tell from logs).

**Comment by MarkElf** [comment]
My apologies then, The starting log can be found here: http://pastebin.com/Vd9YEuas. The gap would be the plugins that load. When using /vault-info ingame, it states "Unknown command. Type "/help" for help". I'm running the latest version of Vault on bukkit (1.5.3). I'll try running vault on a blank server when I get a chance since I was going to go through and each plugin to see if there is a conflicting one anyway.

**Comment by MarkElf** [comment]
It appears that multiverse portals was causing the issue somehow, after removing it, the server seems to have started up without any issues. Thanks for your time @Sleaker .

**Comment by Sleaker** [comment]
@MarkElf  - Glad you found the issue! Not sure why or how Multiverse was causing the problem, but atleast it's all working now.
