### ISSUE TITLE
Vault Issue 

### ISSUE THREAD

**Issue by DubberzGaming** [MilkBowl/Vault#615]
Installed the plugin and downloaded it from the bukkit website and i keep getting this even when it's enabled 
(14.08 18:03:49 [Server] WARN Vault is not enabled! Disabling permissions and economy based variables!)
I have Bettershops and iconomy with this plugin

**Comment by Sleaker** [comment]
looks like one of the plugins is not detecting Vault is installed.  I need more of the log to be able to help.  Is Vault showing up in the startup log?  Is Vault detecting iConomy?  If it is, this is an issue with the plugin you're trying to use.

**Comment by DubberzGaming** [comment]
I don't know how to check my start up log or if iconomy has found it

Connor

**Comment by Sleaker** [comment]
Sorry, I can't help you if you can't provide logs that show what is getting loaded on the server.

**Comment by DubberzGaming** [comment]
I can send the whole entire log if that would help?

Connor

**Comment by Sleaker** [comment]
Pastie.org, pastebin.org or gist.github.com for pasting log files. And then send the link over and that should work.

**Comment by DubberzGaming** [comment]
http://pastebin.com/FvHqN3Cc

This is the latest log I have available.

**Comment by Sleaker** [comment]
You do not have Vault installed on your server. You need to download it and put it in your plugins folder. In addition, you have multiple plugins that are not made for server (optifine) and/or require a different version of the server software to work properly.

**Comment by DubberzGaming** [comment]
I installed it through the shockbyte plugin section, would you be able to
inform them that it isnt downloading correctly and i dont know any other
software to install to get the server to fully function.

**Comment by DubberzGaming** [comment]
[image: Inline image 1]
This shows its installed in the plugins and for some reason its auto
disabled.

**Comment by DubberzGaming** [comment]
sorry to waste your time but i have it working now, please contact
shockbyte to either remove it from their system or to fix the problem and i
had to download Protocollib, could you add that into the MUST need with
vault please to help others. Thank you for your help.

**Comment by Sleaker** [comment]
ProtocolLib is not required for Vault. If you're using a hosting provider you should inform them of issues you have installing plugins. None of the issues you described are in any way related to Vault itself.
