### ISSUE TITLE
Vault fails to load due to Multiverse portals combined with either ChatPing, EnjinMinecraftPlugin or LiftSign and another unknown plugin.

### ISSUE THREAD

**Issue by Drift91** [MilkBowl/Vault#616]
I get the following Error: http://pastebin.com/30gb6w7y

Here's an archive of all the plugins I'm using: https://www.dropbox.com/s/dd8y4xvslzk6w8x/plugins.rar?dl=0

So far I've discovered that disabling Multiverse Portals seems to solve the issue. Another solution I found was to disable ChatPing, EnjinMinecraftPlugin *AND* LiftSign. Disabling only one or two of them doesn't seem to fix the issue. Also if I delete the rest of the plugins I don't get the error. I'm still looking into finding the other culprit(s).

This probably isn't a problem with Vault, but I'm at a complete loss as to who to report this to since there's so many different combinations of plugins that cause it.

**Comment by Sleaker** [comment]
This is not an issue with Vault.

**Comment by Favorlock** [comment]
Sorry to open an issue that you believe isn't resolved, but I have a few users stating this is an issue for them yet I have been unable to find any reason for EMP causing this issue. We only check if Vault is loaded and access it as described in Vault documentation. We don't try to load/unload Vault. If you have any suggestions as to what I should be looking for in EMP I'm all ears, but I've yet to reproduce this issue in my development environment. Sometimes it works with Vault while other times it doesn't.

**Comment by Drift91** [comment]
@Favorlock I believe the following line of code in Multiverse Portals was conflicting with Vault in my case: https://github.com/Multiverse/Multiverse-Portals/search?utf8=%E2%9C%93&q=vault

Not sure if you've read the other ticket I left with the Multiverse team. But Sleaker said something about Multiverse not softdepending on Vault and then mentioned the above line of code importing classes from it.

If your problem is unrelated then you might want to make a separate ticket. I'll let Sleaker handle it from here as I'm just an end-user.

**Comment by Sleaker** [comment]
@Drift91 - yah, not much I can do. I thought multiverse team said they fixed the issue, but if they haven't or if someone hasn't updated to a fixed version then it will still be a problem. It's not an issue with Vault though.
