### ISSUE TITLE
Other download locations than dev.bukkit.org

### ISSUE THREAD

**Issue by Fusix** [MilkBowl/Vault#617]
Hey,
I got a question. Is it allowed to offer Vault from my Website? I've linked the dev.bukkit.org page.

Regards
Fusix

**Comment by Sleaker** [comment]
Vault is bound by the terms of the LGPL, if you redistribute it you must also redistribute the source.  Preferably, don't redistribute as I get very minor ad revenue from Curse.com that helps support the effort I've put into keeping it current and available.
