### ISSUE TITLE
Support for Hyperconomy

### ISSUE THREAD

**Issue by aetaric** [MilkBowl/Vault#620]
Greetings!

If you guys get a moment to add support for another economy, could you add in HyperConomy:
http://dev.bukkit.org/bukkit-plugins/hyperconomy/

It features a much more complex economy system than the currently supported economies and it would be nice to hook it with Vault.

**Comment by Noket** [comment]
It may be beneficial to explain in more detail what you mean by 'support'
since HyperConomy seems to be a massive java project ;)

**Comment by Sleaker** [comment]
Vault hooks are no longer coded or included directly into Vault.  Hyperconomy will need to add in the hook themselves utilizing similar methods as seen in Vault.
