### ISSUE TITLE
Missing dot in update checker

### ISSUE THREAD

**Issue by stefvanschie** [MilkBowl/Vault#621]
There's a missing dot in the update checker. It says: "Vault 15.6 is out! You're running 15.5." While it should be "Vault 1.5.6 is out! You're running 1.5.5."

**Comment by AppleDash** [comment]
This seems intentional. https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/Vault.java#L129

**Comment by stefvanschie** [comment]
Seems like, but it's kinda weird to say 15.5 and 15.6, it would be better to have the dot there, so we actually know the real version.

**Comment by Sleaker** [comment]
yah, it's just a formatting issue related to the checker logic. since it's just cosmetic I'm not really woried about it.

**Comment by stefvanschie** [comment]
Would you fix it if I made a pr for it?

**Comment by Sleaker** [comment]
sure!
