### ISSUE TITLE
Receive no money when selling

### ISSUE THREAD

**Issue by WRChicken** [MilkBowl/Vault#629]
Hi,
I've test 2 plugins for be sure this is from Vault.
ItemCase 1.6
SignShop 2.11.0

But I have the same problem for selling.
When I'm trying to buy, I have no problem, my money is withdraw from my account.
But when I'm selling, Everything is fine, I receive confirmation in chat for my sell, I lost my item, BUT I receive no money...

I've try to uninstall Mineconomy... same problem.

Can you help me please.

Spigot 1.8.8
Vault 1.5.6
Mineconomy Recode 1.7.4

Thank you

**Comment by Sleaker** [comment]
Please verify with the Mineconomy Recode developer that they properly support the same API as the original mineconomy. This is going to be an issue with the economy plugin at this point.

**Comment by WRChicken** [comment]
This is what I've think too, but I can remove Mineconomy and try another one, I got the same problem.
If I just use Vault, this is same...

**Comment by Sleaker** [comment]
Vault doesn't handle any actual transactions, it just provides a universal layer for plugins to communicate with. So if it happens with different economies the only thing I can think of is that it's your setup, or the plugin that's trying to use the API.
