### ISSUE TITLE
Vault, Essentials, and PlayerPoints not playing well together.

### ISSUE THREAD

**Issue by csorrows** [MilkBowl/Vault#635]
I am using:
>Vault v1.5.6-b49
>Essentials TeamCity
>PlayerPoints v2.1.3
>Spigot git-Spigot-fdc1440-53fac9f

When a new player joins, they have no money or PlayerPoints.
If you add money "/eco set {player} {amount}" no plugin outside essentials can see the balance. They see $0.

After a bit of trial and error, I found that if I add even just 1 PlayerPoint to the player, everything talks just fine, PlayerPoints and Essentials money reports correctly to all plugins.

Edit: I am now finding that using '/eco set' or '/points set' will change BOTH currencies. I'm pretty sure I have it setup correctly but I'm not 100% sure I do.

**Comment by csorrows** [comment]
I just set PlayerPoints to not use Vault and it seems to be working fine for now. Closing until/if the problem resurfaces.

**Comment by Sleaker** [comment]
seems like an issue in PlayerPOints.  Vault is a passive handler plugin that routes econ calls, it doesn't actually perform the logic you are describing.

**Comment by csorrows** [comment]
I'm assuming most plugins hook PlayerPoints directly anyway. The Vault support was a recent addition.
