### ISSUE TITLE
latest version error

### ISSUE THREAD

**Issue by SHPkingdoms** [MilkBowl/Vault#637]
ERROR ============================================== 07.11 23:37:04 [Server] ERROR http://dev.bukkit.org/server-mods/vault/ 07.11 23:37:04 [Server] ERROR You can find the latest version here: 07.11 23:37:04 [Server] ERROR Please install Vault first! 07.11 23:37:04 [Server] ERROR Vault is required by this plugin for economy support! 07.11 23:37:04 [Server] ERROR ==================== Jobs ====================

**Comment by Sleaker** [comment]
That's a separate plugin telling you that you need to install Vault for the plugin to work. This is not vault itself.  I'm not sure what your issue here is.

**Comment by Sleaker** [comment]
Please re-open this issue if you are able to describe a specific problem you are having with Vault. Otherwise, please refer to the plugin that is erroring for more help.
