### ISSUE TITLE
Permissions NoSuchMethodError

### ISSUE THREAD

**Issue by austinpilz** [MilkBowl/Vault#638]
Running Vault 1.5.6 and using the same version in my plugin to attempt to gather player groups for that world: 

My Code:
ServerSync.vault.vaultPermission.getPlayerGroups(world.getName(), offlinePlayer)

The Error:
23.12 16:38:12 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getPlayerGroups(Permission_PermissionsEx.java:252) ~[?:?]
23.12 16:38:12 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getUser(Permission_PermissionsEx.java:243) ~[?:?]
23.12 16:38:12 [Server] INFO java.lang.NoSuchMethodError:

**Comment by Sleaker** [comment]
Need the rest of the stack trace along with what version of PermissionsEx you're using.

**Comment by Sleaker** [comment]
Closing this, Closing due to lack of response. Please re-open if you have the requested information. Thanks!
