### ISSUE TITLE
I need support for my new essentials plugin EssentialsZ i recreated Essentials and made all dir paths Fast cleaned up code and more

### ISSUE THREAD

**Issue by zachrose14** [MilkBowl/Vault#639]

**Comment by Badcholo** [comment]
i'll like to test out these essentialsZ, you got a link?

**Comment by zachrose14** [comment]
https://www.spigotmc.org/resources/essentialsz.16731/

Its the essentials source code but im making it 1.7-1.9 compat

**Comment by Sleaker** [comment]
Plugin links should be created in the plugin directly and maintained by the author now.
