### ISSUE TITLE
NPE @ Permission_GroupManager.java#L379

### ISSUE THREAD

**Issue by Favorlock** [MilkBowl/Vault#640]
Getting a null pointer exception at https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/permission/plugins/Permission_GroupManager.java#L379

**Comment by Sleaker** [comment]
need more information that just you're getting an NPE here. What versions of each plugin you're using, the full stacktrace message, what triggered the error etc.

**Comment by Sleaker** [comment]
Closing due to lack of response. If you can provide more information please do re-open.
