### ISSUE TITLE
Vault Hooks and Unhooks my permissions

### ISSUE THREAD

**Issue by PhantomQ** [MilkBowl/Vault#641]
I'm helping a friend setup his files on his server. I've done the same basic setup as on my own server (Which works fine) but on his it isn't working. 
When the server starts, it says: 

[Server] INFO Enabled Version 1.5.6-b49
[Server] INFO [Permission] SuperPermissions loaded as backup permission system.
[Server] INFO [Permission] PermissionsBukkit found: Waiting
[Server] INFO [Vault][Permission] PermissionsBukkit hooked.
[Server] INFO [Economy] Essentials Economy found: Waiting
[Server] INFO Enabling Vault v1.5.6-b49

However once the server is fully loaded it then says:

[Server] INFO Using superperms-based permissions.
[Server] WARN Features such as chat prefixes/suffixes and group-related functionality will not work
                            until you install Vault.
[Server] WARN Detected supported permissions plugin PermissionsBukkit without Vault installed.
[Server] INFO [Vault][Economy] Essentials Economy hooked.

However, vault isn't disabled or become disabled. This wouldn't be an issue if he didn't want to be able to display prefixes.

**Comment by PhantomQ** [comment]
Additionally, inputting the command /vault-info in game says:

"[Vault] Permission: PermissionsBukkit [PermissionBukkit, SuperPerms]

**Comment by Sleaker** [comment]
Sounds like your chat plugin isn't detecting vault properly even though Vault is installed. Not really an issue with Vault.
