### ISSUE TITLE
Vault cannnot be found

### ISSUE THREAD

**Issue by IanLim2024** [MilkBowl/Vault#642]
Help i am running minecraft 1.8.3 server i used the method that milkbowl gave to hook vault i have the latest vault installed but it still says no vault dependancy found

**Comment by Sleaker** [comment]
If you would like help you will need to give a link to a pastebin of your startup log on the server, and the code you're using to link into vault.

**Comment by Sleaker** [comment]
Closing this. If you have more information please re-open so I can help with getting you setup.
