### ISSUE TITLE
"Loan was not permitted"

### ISSUE THREAD

**Issue by RianOBrian** [MilkBowl/Vault#644]
Whenever a player tries to buy a ticket in my lottery plugin, even if they have the amount of money required, it sends them the message: "Loan was not permitted". If they are receiving money, it works fine but if they're losing money as in it being taken away from them, it doesn't work.

**Comment by Sleaker** [comment]
Check with what economy and lottery plugin you are using. Sounds like they aren't doing something properly or there is a misconfiguration.

**Comment by RianOBrian** [comment]
Hi. I am using essentials economy and a lottery plugin that I made

**Comment by Sleaker** [comment]
Can't really help you here. It sounds like you have Essentials Economy misconfigured.
