### ISSUE TITLE
maps in itemframes

### ISSUE THREAD

**Issue by GunneR007** [MilkBowl/Vault#646]
Ok were do i start well i download vault work fine until i put a map in a item frame then it says i cant put a map in a item frame but when i take vault out i can so i put vault back in and it says i cant so i thought it was another plugin doing this so i took each plugin one by one and nothing it is vault stopping me from doing this is there a way to fix this issue.

**Comment by trainphreak** [comment]
Please be sure to answer ALL of these questions:

What Vault version are you using?
What server are you using (Bukkit, Spigot, etc)?
What version of that server are you using (please give both the Minecraft version and the download version)?

**Comment by Sleaker** [comment]
Vault has no hooks for player interaction by itself so I can say 100% this is not Vault.

You may have a plugin that is not being enabled when Vault is not present, but then when you do add Vault it starts doing it's stuff to item frames. Please check your startup log for anything that may be interacting or not enabling in both cases and then submit bugs to that plugin.
