### ISSUE TITLE
1.9

### ISSUE THREAD

**Issue by boredherobrine13** [MilkBowl/Vault#647]
Update to 1.9?

**Comment by Botanistt** [comment]
why if it works fine?

**Comment by woutwoot** [comment]
It does work, but some things are missing. The Items API does not contain 1.8 items yet, for example.

**Comment by boredherobrine13** [comment]
Exactly, and now its 1.9. I might fork it and update it myself at this point.

**Comment by woutwoot** [comment]
I believe someone already forked it and updated the API [here](https://github.com/Sycholic/VaultAPI). The pull request was not approved yet though.

**Comment by Sleaker** [comment]
Closing as this issue doesn't include relevant information.
