### ISSUE TITLE
Error with 1.9

### ISSUE THREAD

**Issue by LaughNgamez** [MilkBowl/Vault#649]
I get this error with 1.9

http://pastebin.com/kBHCjj3c

help is appreciated.

**Comment by woutwoot** [comment]
You are using an old version... Download the latest version from [bukkitdev](http://dev.bukkit.org/bukkit-plugins/vault/files/52-vault-1-5-6/). (1.5.6)

**Comment by LaughNgamez** [comment]
Hmm silly me, thanks.
