### ISSUE TITLE
Missing Method

### ISSUE THREAD

**Issue by MCMatzeHD** [MilkBowl/Vault#652]
Hi,

I using Vault (v1.5.6-b49) with PermissionsEx (v1.23.4).
I developing a Plugin for my server and have hooked Vault and it's working.
But: When I add a group to a player, it's only add the rights to the world, where the player is standing
("permission.playerAddGroup(Player, Group);"). I also can use a foreach-loop and regeister it to all worlds, but when I create a new world? Why I dont set the rank for all worlds like the pex-command /pex group (group) user add (player) ? I dont kown about an other method, that do it like I mean.

Please help.
MCMatzeHD

Sorry for bad englisch :(

**Comment by Sleaker** [comment]
Please read the documentation in the API, method/source it details exactly what the methods do and which ones to use for non-world specific permission changes.
