### ISSUE TITLE
Error installing on proxy

### ISSUE THREAD

**Issue by MeAngel** [MilkBowl/Vault#654]
For some reason I cannot get Vault to be enabled on this server.

Yes, I'm ignorant - absolutely - where a network set up is involved. But can you perhaps tell me why I might be getting this error?

This is what I received after adding the Vault plugin to my server plugin folder and restarting it:
http://pastebin.com/AiEdrhPT

**Comment by Sleaker** [comment]
the paste expired. could you repost?

**Comment by AppleDash** [comment]
@MeAngel Are you trying to install this plugin on BungeeCord's plugins folder? If so, you don't need to - it goes on the Spigot servers only.

**Comment by MeAngel** [comment]
Thank you for the replies, yes, Apple I had been originally, and then because I'm persistent when I can't get answers in the same day I kept asking around and was informed how that works later in the day. So my question has been answered; thank you for taking the time to respond and reminding me to close this. :)

**Comment by Sleaker** [comment]
Ahh right, I mis-interpreted the initial report. Vault is not a proxy plugin. it is only for servers running the bukkit interface.
