### ISSUE TITLE
Plugin is already initialized?

### ISSUE THREAD

**Issue by itskun** [MilkBowl/Vault#655]
Catching an exception while starting server 1.7.10 Thermos.
![default](https://cloud.githubusercontent.com/assets/9961535/14987936/51511b12-115a-11e6-9c05-767aa7a23105.PNG)

**Comment by itskun** [comment]
Sorry, A have an Multiverse Portals, which causes this problem.

**Comment by Sleaker** [comment]
@itskun  - all good! I thought they had updated with a fix though. maybe check versions?
