### ISSUE TITLE
Problem command vault-convert

### ISSUE THREAD

**Issue by Res83** [MilkBowl/Vault#660]
Hello my server is spigot 1.10 and use Gringotts and Essentials

/vault-convert EssentialsEconomy Gringotts

`{\rtf1\ansi\ansicpg1252\deff0\deflang11274{\fonttbl{\f0\fnil\fcharset0 Arial;}}
{\colortbl ;\red0\green0\blue255;\red255\green0\blue0;}
\viewkind4\uc1\pard\cf1\fs18 10:06:48 p. m. [INFO] CubyMaster issued server command: /vault-convert EssentialsEconomy Gringotts\par
10:06:48 p. m. [SEVERE] null\par
10:06:48 p. m. org.bukkit.command.CommandException: Unhandled exception executing command 'vault-convert' in plugin Vault v1.5.6-b49\par
\cf2 10:06:48 p. m. \tab at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.jar:git-Spigot-c55900f-9856d8a]\par
10:06:48 p. m. \tab at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.jar:git-Spigot-c55900f-9856d8a]\par
10:06:48 p. m. \tab at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.jar:git-Spigot-c55900f-9856d8a]\par
10:06:48 p. m. \tab at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]\par
10:06:48 p. m. \tab at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]\par
10:06:48 p. m. \tab at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]\par
10:06:48 p. m. \tab at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]\par
\cf1 10:06:48 p. m. \tab at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]\par
\cf2 10:06:48 p. m. \tab at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]\par
10:06:48 p. m. \tab at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]\par
\cf1 10:06:48 p. m. \tab at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]\par
\cf2 10:06:48 p. m. \tab at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]\par
10:06:48 p. m. \tab at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]\par
10:06:48 p. m. \tab at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]\par
10:06:48 p. m. \tab at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]\par
10:06:48 p. m. \tab at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]\par
10:06:48 p. m. Caused by: java.lang.NoSuchFieldError: accountHolderFactory\par
10:06:48 p. m. \tab at net.milkbowl.vault.economy.plugins.Economy_Gringotts.hasAccount(Economy_Gringotts.java:125) ~[?:?]\par
10:06:48 p. m. \tab at net.milkbowl.vault.economy.AbstractEconomy.hasAccount(AbstractEconomy.java:10) ~[?:?]\par
10:06:48 p. m. \tab at net.milkbowl.vault.Vault.convertCommand(Vault.java:461) ~[?:?]\par
10:06:48 p. m. \tab at net.milkbowl.vault.Vault.onCommand(Vault.java:412) ~[?:?]\par
10:06:48 p. m. \tab at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.jar:git-Spigot-c55900f-9856d8a]\par
\cf1 10:06:48 p. m. \tab ... 15 more}
`

**Comment by Sleaker** [comment]
Looks like the version of Gringotts you are using may not be compatible with the Vault adapter.
