### ISSUE TITLE
Issues with offline mode/EssentialsEco  implementation

### ISSUE THREAD

**Issue by galacticwarrior9** [MilkBowl/Vault#662]
Details here: https://github.com/drtshock/Essentials/issues/555

This occurs when I set HyperConomy to use an external econony (use-external-economy: true), in this case EssentialsEco in offline mode.

Here's what the HyperConomy author had to say about it:

> It looks like this may be an issue with EssentialsX which was somehow triggered by HyperConomy. I'm unable to reproduce it so far. Does this occur each time you start your server? If it does sending me a copy of your database might be helpful in narrowing down the cause. The error itself appears to be created by a recursion loop in the Essentials_Economy class of the Vault plugin. The depositPlayer function recursively calls itself and gets stuck in a loop. Apparently it keeps throwing a UserDoesNotExistException after the createPlayerAccount function fails repeatedly. This is very likely to be an EssentialsX issue based on the logs. Something unusual in HyperConomy might be triggering it though. 

Sample error log (error starts at line #1001)
http://pastebin.com/7mCXtMYm

@drtshock said the following:

> Looks like it could be an issue in vault's implementation of esseco perhaps.

Is a fix possible? It's crippled my entire server economy as getting HyperConomy to hook its internal economy into Vault creates all sorts of weird issues with Essentials such as having two seperate balances which can't interact with each other.

**Comment by Sleaker** [comment]
The only way it can enter into a loop is if user accounts can't be created.  Under no circumstances should that fail.
