### ISSUE TITLE
Nobody can login on the server, unless I remove vault.jar

### ISSUE THREAD

**Issue by Sikatsu** [MilkBowl/Vault#663]
Hey,

Somehow, while I didn't change anything at all, after the server restart nobody can login on the server anymore.

If I remove vault.jar, everyone is able to login but it breaks plugins ofcourse.

How can I fix this?

/
mc.villagercraft.eu 

Logging in...
Timed out
/

**Comment by Sleaker** [comment]
vault doesn't prevent/interact with logins in a way that would cause this. most likely you have some plugin that's enabling functionality due to seeing vault. some plugins turn themselves off when vault is not installed, or disable certain features, this is most likely what is going on.

**Comment by Sikatsu** [comment]
The weird thing is, I've removed all the plugins from my server, put them one by one, and as soon as I added vault.jar, nobody could login anymore. When I removed all plugins except vault and dynmap, I still could not login.

Therefor I thought it was really related to vault somehow. Anyways, after 2hours people were able to login again, without a restart.. I wonder what made it work after 2 hours then without doing anything. (As I didn't know what to do)

**Comment by Sleaker** [comment]
sounds like you have dynmap setup to do something and it took 2 hours to do...

**Comment by Sikatsu** [comment]
Dynmap is pre rendered and doesn't do anything. Also when I removed vault.jar it worked, so I don't think this is dynmap related. Why would a plugin block people from logging in?

**Comment by Sleaker** [comment]
I dunno, hardware problems maybe? Vault does a quick permission check on players on login but it's not doing anything special, just prints a message, and other servers are not able to replicate this issue. I can't really help you here as it's not replicate-able and does not look like it has anything to do with vault.
