### ISSUE TITLE
Can't convert craftconomy to iconomy

### ISSUE THREAD

**Issue by xion87** [MilkBowl/Vault#665]
I am trying to convert crafyconomy 3 to iconomy7  (i am using a updated fork http://dev.bukkit.org/bukkit-plugins/iconomy-7/)
I tried to do convert with vault but conversion will fail imediatly (it finish after 1 second), any clues?

**Comment by Sleaker** [comment]
No clues. I would need server logs that show something trying to happen to even start helping with this.

**Comment by xion87** [comment]
nevermind, is working :) with latest dev crafconomy :D
