### ISSUE TITLE
Error with SignShop

### ISSUE THREAD

**Issue by Serux18** [MilkBowl/Vault#672]
From page Signshop have sent me here because they believe it is an error of vault
https://dev.bukkit.org/bukkit-plugins/signshop/tickets/689-grave-error-and-lag/

Spigot 1.8.8
Vault: 1.5.6-b49
SignShop version: 2.11.0Dev (latest dev)
Essentials manages the economy (EssentialsX 2.0.1)
ZPermissions 1.3

It is a mistake that leads days appearing on the console and causes the server to go very slow when it occurs

I imagine that is when a user clicks on a sign but do not know what it is or where it is
Clarify that in some specific cartel, others are good, but I can't get to find him

http://pastebin.com/vpM3tpAu

**Comment by Sleaker** [comment]
This means your server is not setup properly, or the creation of accounts is failing. the codeblock in the Essentials connector was requested to be done like that per Essentials.
