### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Sitmobedaf** [MilkBowl/Vault#673]
http://pastebin.com/u9BrLYdn

**Comment by RianOBrian** [comment]
"C:\Users\SiT\Downloads\Vault-master\build.xml:6: destination directory "C:\Users\SiT\Downloads\Vault-master\${build}" does not exist or is not a directory"

Taken from your Pastebin upload. Please check if "C:\Users\SiT\Downloads\Vault-master\${build}" exists. If it doesn't there's your problem. If it does exist, please tell me and I'll try to help you more.

Thanks,
Rian

**Comment by Sleaker** [comment]
Ant build is deprecated. please use maven.
