### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by JugadorON** [MilkBowl/Vault#674]
https://dev.bukkit.org/bukkit-plugins/vault/

I need version to 1.10.2, please!!!

Java 8!

**Comment by RianOBrian** [comment]
Hi @JugadorON,

It should work for 1.10.2. I use it on my server at home.

If it doesn't, please upload your errors to [Pastebin](http://pastebin.com).

Thanks,
RianOBrian

**Comment by Sleaker** [comment]
'Update for version x issues' are not valid, Vault is forward compatible with no updates unless some drastic internal change occurs.
