### ISSUE TITLE
1.11 support.

### ISSUE THREAD

**Issue by TheIntelloBox** [MilkBowl/Vault#675]
Hello ! :D 

Could you someone update this plugin to 1.11 please ? :D 

Thanks ! :D

**Comment by OffLuffy** [comment]
Although I don't get an error, I also can't seem to get Vault to cooperate on 1.11. It seems that the methods to setup Vault returns null for whatever reason. The code I use (which I believe comes from the Vault documentation):

`private static boolean setupPerm() {
		RegisteredServiceProvider<Permission> pp = Bukkit.getServicesManager().getRegistration(Permission.class);
		if (pp != null) perm = pp.getProvider();
		return perm != null;
	}`

**Comment by Favorlock** [comment]
I would assume it's likely an issue with another plugin as Vault should work on 1.11 unless there were some major changes to the Bukkit API that the plugin relies on.

**Comment by Sleaker** [comment]
No update required for it to 'just work' out of the box. Unless major changes happened it will work fine.
