### ISSUE TITLE
Vault + Any Economy Plugin = Inventory Splits

### ISSUE THREAD

**Issue by freakyy85** [MilkBowl/Vault#676]
Using any Economy plugin (RoyalEconomy, Fe)  both plugins make Inventory glitches. If you run Fe and Vault and have say 40 wood. place 20 above the other, then shift+rightclick, the plugin combination will make like 10-6-something stacks. instead of counting up to 64 (fulls tack). this happens also when picking up eg. seeds.
can you please fix this?

Heres a video: https://youtu.be/s_Dt9KBkk5Q

**Comment by Sleaker** [comment]
This is not a bug in Vault, vault does not interact at all with player inventory and can't produce the bugs on it's own. This may be a result of some functionality that is turned on in another plugin when it detects vault is loaded.
