### ISSUE TITLE
Endless stream of "Couldn't save chunk" errors after moving to 1.11.2 Spigot

### ISSUE THREAD

**Issue by gerardvanschip** [MilkBowl/Vault#680]
In my startup log I noticed a HUGE stream of chunk errors right after installing 1.11.2. I did not have this error on 1.11

http://pastebin.com/aBh7whnq

Also curious if the plugin is still in development seeing it was last updated in August 2015 where it states its 1.8.1 compatible.

**Comment by no372** [comment]
Well, those errors never mention Vault anywhere...

**Comment by gerardvanschip** [comment]
I found out what the problem was, it was a shop plugin which was updated at the same time. Please close this.
