### ISSUE TITLE
Permission/Permission Group Change Event

### ISSUE THREAD

**Issue by regice202** [MilkBowl/Vault#681]
Heyo! I'm writing a plugin called Linkup which links MC server groups to different platforms such as TeamSpeak, Discord, and hopefully more in the future. Anyways, I already have it so that when a player rejoins the server, the plugin is loaded, or an update command is run, their groups are automagically updated. So you only have to linkup once! It would be absolutely epic if you could add this event though, then whenever someone is added or removed from a group, I can automagically update them on all of the platforms they've linked to, no extra commands, rejoins or reloads/restarts required! Thank you for your time and consideration!

- regice202

**Comment by Sleaker** [comment]
Please see all of the previous issues on this: https://github.com/MilkBowl/Vault/issues?utf8=%E2%9C%93&q=is%3Aissue%20events
