### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by ICEconchy** [MilkBowl/Vault#683]
I found this in the console:

[Vault] Task #2 for Vault v1.5.6-b49 generated an exception java.lang.NoClassDefFoundError: net/milkbowl/vault/Vault$1$1 at net.milkbowl.vault.Vault$1.run(Vault.java:159) ~[?:?] at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-6016ac7-10c10b3] at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-6016ac7-10c10b3] at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [server.jar:git-Spigot-6016ac7-10c10b3] at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-6016ac7-10c10b3] at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [server.jar:git-Spigot-6016ac7-10c10b3] at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [server.jar:git-Spigot-6016ac7-10c10b3] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74] Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.Vault$1$1 at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_74] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-6016ac7-10c10b3] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-6016ac7-10c10b3] at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74] ... 8 more

Latest version

**Comment by Sleaker** [comment]
Are you trying to load Vault multiple times or have a bad download of it? It's saying it can't find the Vault main class..
