### ISSUE TITLE
Unable to hook economy

### ISSUE THREAD

**Issue by xeu100** [MilkBowl/Vault#686]
I just attempted to integrate Vault with my custom Economy Plugin instead of its own API functionality. When trying to do this, it doesn't register and continues to use Essentials. I have set the priority to highest within what I am told is the correct method to implement. I have created a class with the implement of Economy.

**Comment by Sleaker** [comment]
Make sure you setup your economy to load in startup and depend on vault. All you're doing is registering the service for use in the bukkit service manager other plugins will pick it up, but wont do so if it's not loaded yet which is why you have to make sure it gets loaded before it could be used.
