### ISSUE TITLE
SaneEconomy Support?

### ISSUE THREAD

**Issue by smmmadden** [MilkBowl/Vault#687]
Hi - I've recently migrated from using Fe Economy plugin to using SaneEconomy for each of our worlds.  I'm using EssentialsX as well, but that's not currently used for the financial part of the application.

So my question is, do you offer support to [**SaneEconomy**](https://github.com/drtshock/Essentials) and [**EssentialsX**](https://www.spigotmc.org/resources/saneeconomy-simple-but-featureful-economy.26223/) or do we still need to use this version of [**Vault**](https://dev.bukkit.org/projects/vault)?

**Comment by TheIntelloBox** [comment]
I think you will never have an answer here. xD

**Comment by Sleaker** [comment]
@smmmadden - the Vault version you linked is the most recent version. I don't support economies by default in Vault any longer, it's up to the economy implementation to provide their own Vault hooks if they want it to work with the Vault API.
