### ISSUE TITLE
Support for LuckPerms

### ISSUE THREAD

**Issue by martinambrus** [MilkBowl/Vault#688]
Hi guys,

any plans to add [LuckPerms](https://github.com/lucko/LuckPerms/wiki/Developer-API) support? I could do it and post a pull request, if that'd be easier?

Cheers :)

**Comment by kanoxx** [comment]
LuckPerms already brings Vault support with itself.
See these files:

- https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/java/me/lucko/luckperms/bukkit/vault/VaultHook.java

- https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/java/me/lucko/luckperms/bukkit/vault/VaultPermissionHook.java

**Comment by martinambrus** [comment]
Ah, I had no idea, sorry. I'll ping them to update their docs, thank you!
