### ISSUE TITLE
Thermos problem generating config file

### ISSUE THREAD

**Issue by plaguewolf** [MilkBowl/Vault#701]
Not vault's fault, at all. but could someone please post their config for vault 1.4.1?

Thermos 58 seems to derp on config generation for quite a few plugins, and i haven't the faintest idea why.

**Comment by Sleaker** [comment]
Vault doesn't really need a configuration, it has 1 option that can be seen here.

https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/Vault.java#L132
