### ISSUE TITLE
vault-convert EssentialsEconomy XXXXX does not work

### ISSUE THREAD

**Issue by Rocologo** [MilkBowl/Vault#704]
So I found out how to hook into Vault, but when I tried to use 

>vault-convert EssentialsEconomy BagOfGold

in the console It did not work???

[14:43:46 INFO]: This may take some time to convert, expect server lag.
[14:43:46 INFO]: Converson complete, please verify the data before using it.

But the Essentials balance was not converted to BagOfGold balance.

Any ideas?

**Comment by Sleaker** [comment]
Convert doesn't necessarily work with every balance type.
