### ISSUE TITLE
Switch MCStats to another Metrics provider.

### ISSUE THREAD

**Issue by DoNotSpamPls** [MilkBowl/Vault#706]
MCStats has been in a half-broken state for years now, and it doesn't seem like the developer is going to fix it

**Comment by TWSSYesterday** [comment]
https://bstats.org/ would be the obvious choice to move to.

**Comment by Sleaker** [comment]
I'll be removing the old mcstats integration with the next update.

**Comment by DoNotSpamPls** [comment]
@Sleaker there are 3 reasons

1. The static.mcstats.org server is running very slow for some reason, and this results in half-working webpages like this ![](https://bitcoin.is-serious.business/c3e783.png). The author of MCStats is nowhere to be found to fix it.
2. Even if you manage to open the plugin stats page, location maps just show "Unknown" as a location, and some charts just don't load at all
3. This is pretty minor, but passwords in MCStats are stored as SHA1, which is known to be vulnerable. bStats uses bcrypt, which is a significantly better hashing algorithm.

**Comment by maxlehot1234** [comment]
@Sleaker Update vault and remove mcstats and use bstats ;)

It was just amazing to see a plugin works 3 years after the last update ;)

NICE JOB btw

**Comment by NiklasEi** [comment]
@Sleaker If it's fine with you, I would like to make a pull request for this. I've been using bStats in my own plugins for a while now and really like it.
The custom graphs from vault's metrics class can also be implemented for bStats.

**Comment by DoNotSpamPls** [comment]
@NiklasEi Sleaker will have to contact Bastian (the owner of bStats) in order to get the "vault" plugin that's there deleted (it was a fake version posted by a user called kanoxx, it's now gone from spigot resources)

**Comment by conreptio** [comment]
@DoNotSpamPls
1. It is not a fake version
2. I (kanoxx) can give him the plugin name without any trouble

**Comment by DoNotSpamPls** [comment]
Sorry, "fake" was probably the wrong word. I meant that it's kind of unofficial. Thanks for coming in though :smiley:

**Comment by Sleaker** [comment]
@conreptio - This PR has been completed and I have an account on bstats.org - can you transfer the ownership over to me? Thanks!

**Comment by Bastian** [comment]
Hey, 👋
I need your exact bStats name (case sensitive!) in order to transfer the account.
Is it 'Sleaker'?

**Comment by Sleaker** [comment]
@Bastian it is!

**Comment by Bastian** [comment]
Done 👍
