### ISSUE TITLE
Maintaining vault

### ISSUE THREAD

**Issue by wherkamp** [MilkBowl/Vault#711]
I am wondering if you are welcome to having someone else take over Vault?

**Comment by silverforte** [comment]
At a certain point, for the good of the community, someone needs to just do it.

**Comment by wherkamp** [comment]
I am up for the challenge that is why I was asking.

**Comment by Sleaker** [comment]
I'll be releasing an update for 1.13. no need to worry about maintenance.

**Comment by wherkamp** [comment]
Will it be being published on Spigot not Bukkit dev.

**Comment by Sleaker** [comment]
Why would I publish it on spigot?

**Comment by wherkamp** [comment]
Because Spigot is the living part of Bukkit.

**Comment by silverforte** [comment]
Why wouldn't you?...

**Comment by Sleaker** [comment]
sorry, I forgot I already had it up on spigot. yes it'll be available there.

**Comment by wherkamp** [comment]
Good because Spigot > Bukkit/curse.
