### ISSUE TITLE
playerAddGroup replaces current group

### ISSUE THREAD

**Issue by basdv98** [MilkBowl/Vault#712]
When using the following method, the player defined in "player" will get the "testgroup" group but it will replace the group that the player was already in. Instead I want it to add the group as the method says.

`perms.playerAddGroup(null, player, "testgroup");`

I am using PermissionsEX as my permissions plugin. Please let me know how to solve this issue.

**Comment by Sleaker** [comment]
Please check with PermissionsEX on proper ways to add groups to players. iirc this may be a result of you trying to add a group to a player not bound to a world.. either way this is in the implementation of PermsEX not Vault.
