### ISSUE TITLE
Content Management Interface (CMI) economy addition.

### ISSUE THREAD

**Issue by LogGits** [MilkBowl/Vault#713]
Hey, would it be possible if vault could have CMI economy internally supported, similar to how essentials is implemented. [CMI](https://www.spigotmc.org/resources/cmi-ranks-kits-portals-essentials-mysql-sqlite-bungeecord.3742/) is a premium, Multipurpose plugin that has a built in economy that utilises vault. The only issue is that it needs a seperate injector plugin to work with other plugins that also utilise vault. If we develop an implementation and send a pull request would you be able to add the addition into the project?

**Comment by Sleaker** [comment]
I'm not sure what you're asking for here, are you wanting to add a default economy implementation to Vault? CMI is a premium plugin so I'm not sure what you're requesting.

**Comment by LogGits** [comment]
> I'm not sure what you're asking for here, are you wanting to add a default economy implementation to Vault?

Yes, CMI does need default economy implementation in vault.

> CMI is a premium plugin so I'm not sure what you're requesting. I'm also not sure why you need some form of injector to make it work... just add an optional dependency on Vault put all the injector code into CMI, and be done with it.

CMI relies on vault to interact with other plugin economy systems. The issue that forces CMI to actually need a seperate injector is that CMI needs to load after many other plugins. The down side of this is that it needs a seperate injector to actually correctly run with other economy based plugins. Hardcoded support for CMI would ensure the best compatibility.

If we write up a pull request, would you be willing to merge it into the latest build?

**Comment by Sleaker** [comment]
No. Manage your own connectors. I see no reason why you can't manage and maintain a connector plugin as an add-on for your own premium plugin.
