### ISSUE TITLE
Ultra Permissions support

### ISSUE THREAD

**Issue by pixar02** [MilkBowl/Vault#714]
Could it be possible to add support for [Ultra Permissions](https://www.spigotmc.org/resources/ultra-permissions.42678/)?
It's becoming more and more popular and it would help me alot if it was supported by Vault. If I knew how to do it for you guys I would do it but I don't.

Kind regards,
pixar02

**Comment by Sleaker** [comment]
Vault lets plugins manage their own connectors now. Please ask Ultra Permissions to provide a Vault connector.
