### ISSUE TITLE
current version?

### ISSUE THREAD

**Issue by ShaneBeee** [MilkBowl/Vault#715]
Hello
I am curious which is the appropriate current version.
I see on [BUKKIT](https://dev.bukkit.org/projects/vault/files) the current version is 1.5.6 released in August of 2015
and the current (only) version on [SPIGOT](https://www.spigotmc.org/resources/vault.34315/) is 1.6.6 released in January of 2017.
I just wanted to know which one is actually the correct current version of Vault I should use?
Thank you

**Comment by Sleaker** [comment]
The bukkit version is the correct version. I'm not sure why there's a separate one being hosted on Spigot but it is not official and I'm not in control of publishing it there.

**Comment by Sleaker** [comment]
Ahh, so apparently the version listed on bukkit didn't get updated the last time the API change was made. I'll be updating the bukkit page.

**Comment by ShaneBeee** [comment]
Awesome.  Thank you.  It’s funny because the dude who posted it on spigot said “were the current maintainers” clearly not

**Comment by Sleaker** [comment]
@ShaneBeee - Kainzo manages the release server that's all. there was just a mixup on where it was getting published.

**Comment by rjbradlow** [comment]
eh hem, BUKKIT's current version is still 1.5.6 released in August of 2015.
I find it very amusing that so many plugins that depend on Vault have claimed to be updated to work with 1.12.2, yet Vault is only compatible up to 1.11 (via version 1.6.6 on Spigot)  
-- Ah, Microsoft has to ruin everything. eh? Wish they'd stop ruining / changing / bloating the code... breaking things.  But that's just they way they roll.

**Comment by rjbradlow** [comment]
@Sleaker I did not intend to 'Trigger' you, but thank you for your unwarranted "if I do not like it, GFM" reply. - I'm sure you are sick of the endless self-entitled trolls demanding something for nothing, so I understand if you are touchy.
Not everyone is aware of any or all that you mentioned, and happen to stumble here trying to make sense of what we should do as we search for some clue on whether or not certain plugins will work or crash our servers. - Me a (relative MC noob) father of a 9yo girl obsessed with minecraft trying to protect her from online predators while trying to give her the best experience to share with her known friends - is trying to learn all that he can to that end.

Not everyone has knowledge of Java or even a firm grasp of what they do know enough of to possibly wade through your code. (yet, I am trying to learn.)

Granted your code is available and thank you for your work, but I do not appreciate the arrogance that comes with it for trying to help others by getting some things answered here.

It is not the EUs who have made this mess but the corporate a.holes as you've pointed out, so please keep that in mind for us poor souls who happen across you in our search for answers.

Me, I'm just trying to see some organizational efforts made towards the existing mess.
Is it too much to ask that you just clean up Spigot and Bukkit to point to your github nest and therefore only have One place to explain, edit, and provide attitude?

Thanks! Don't Taze me Bro.

**Comment by Sleaker** [comment]
My comments were simply explanatory in nature as you mentioned you were leery to use the software. 

> Me a (relative MC noob) father of a 9yo girl obsessed with minecraft trying to protect her from online predators while trying to give her the best experience to share with her known friends/

not sure how any of this is relevant to the software question and documentation being made more accurate.

**Comment by ShaneBeee** [comment]
@Sleaker  I was going thru my emails and saw an update to this thread. Reading it has me so confused, as I feel @rjbradlow  is probably in a similar space to me... confusion.
I asked what the current version was, because theres a few different version floating around.
You said
"The bukkit version is the correct version. I'm not sure why there's a separate one being hosted on Spigot but it is not official and I'm not in control of publishing it there."
Now the "latest" version on bukkit is 1.5.6 which was updated almost 3 years ago, for 1.11 .... to some people who dont realize vault doesn't actually need an update, might be confused by this thinking its been abandoned. 
Now you stated youre not sure why theres one being hosted on spigot. When i commented in regards to Kainzo's reply to me on spigot saying "No one has remade vault, we are the original maintainers."
Your reply was
"Kainzo manages the release server that's all. there was just a mixup on where it was getting published."

Heres my confusion. Your latest release on bukkit is 1.5.6 (Aug 2015) and his latest release on spigot is 1.6.6 (Jan 2017)

Im also confused as to why you stated you are not sure why anyone is releasing it on spigot, then telling me Kainzo was in charge of releases.
I feel like there are some serious inconsistencies with your story here. One second you have the latest update and not sure why someone else is updating on spigot, the next second you are telling me that Kainzo is in charge of releases?!?!? 

So which version is actually correct?

I can totally see why RJB was sending the replies he was. He is probably just as confused as I am with all the inconsistency with this thread.

**Comment by Sleaker** [comment]
@ShaneBeee - both are correct. the 1.6.6 version just never got pushed to bukkit. I had forgotten that Kainzo had made a page on spigot to manage it there, which I have no control over.  If you're confused, just keep with the latest version from either of the sites.

**Comment by DoNotSpamPls** [comment]
Uhh, the version on the Bukkit page is still 1.5.6. Any plans to update it?

**Comment by axemwa** [comment]
Stiiiiiill there, update 1.5.6 to 1.6.6 pls. Also someone said there's a 1.5.6-b49 build where can I find that as apparently it works in 1.13

**Comment by bundabrg** [comment]
I was confused as well TBH. This thread (most of which probably doesn't really belong in a github issue but I'm unsure where else) at least cleared up to me that Vault will in general work up to 1.12, though will require some minor changes to fix for 1.13.

**Comment by Sleaker** [comment]
I will be publishing 1.7.1 later tonight.
