### ISSUE TITLE
Unable to make a vault with towny

### ISSUE THREAD

**Issue by Zanzoman** [MilkBowl/Vault#716]
When doing [town vault] it doesn't work for some players and works for other players.
![bad](https://user-images.githubusercontent.com/36989871/39220828-b5296d3c-4872-11e8-95fb-f46cc20fb5ef.png)
This is the recieved error when trying to make said vault.

**Comment by ShaneBeee** [comment]
Um.... i think youre on the wrong plugin, Vault has nothing to do with actual VAULTS.... its just an api plugin to link plugins economy/chat/permission together

**Comment by Sleaker** [comment]
Closed as unrelated.
