### ISSUE TITLE
Integrating an own economy

### ISSUE THREAD

**Issue by dlimerick** [MilkBowl/Vault#717]
Hello,
I read lots of tutorials and so on, but because I am from Germany I am not so good in English, I understand nothing. And now I want to add my own economy API, my problem now is that I don't know how and I don't know how GitHub work.

So is there a way that you can do it for me?

**Comment by Sleaker** [comment]
I'm sorry, I don't have the time to walk someone through development/git process and getting everything setup. You'll need to be able to do basic java development with the bukkit API, and handling of dependencies yourself.  you could ask on bukkit/spigot forums for help with getting setup and developing if there's something you're missing.
