### ISSUE TITLE
Players can't chat in Minecraft with OP status...

### ISSUE THREAD

**Issue by phouff** [MilkBowl/Vault#721]
I just installed Vault, PermissionsX, and Grief Prevention on a brand new server. I fear I have not set it up properly because when I gave my daughter /op status, she can no longer type in the chat box. I just installed the plug-ins on my server console. I didn't change any of the coding anywhere, do I need to? I'm not sure what I did wrong.

**Comment by Sleaker** [comment]
Vault is just a compatibility layer that allows the different plugins to interact with each other, it doesn't actually setup the permissions itself. 
I actually know nothing about either of the 2 plugins you mentioned.  My suggestion would be to direct questions to Grief Protections or PermissionsX as they are the most likely plugins that are limiting access to users on the server being able to chat.
