### ISSUE TITLE
Vault Does Not Recognise Luckperms And Everything Breaks

### ISSUE THREAD

**Issue by parkermeyers25** [MilkBowl/Vault#726]
### **Vault Does Not Recognise Luckperms And Everything Breaks...** 

**Here is the latest log...**
https://pastebin.com/gKkuMmvp

This Is Really Important, please respond.

**Comment by Sleaker** [comment]
Vault loaded just fine. Your issue appears to be elsewhere. It also appears you attempted to live-reload the server/plugins which caused some problems.
