### ISSUE TITLE
1.13 support

### ISSUE THREAD

**Issue by JarlPenguin** [MilkBowl/Vault#729]
Is official 1.13 support planned, or is it not necessary at all?

**Comment by Sleaker** [comment]
it needs some fixups before it'll work on 1.13 due to material changes in MC.

**Comment by crashtheparty** [comment]
When we do get 1.13 support, will it be published on Bukkit, Spigot, or some other website, or will we have to build it from the source code on git?

**Comment by Roper89** [comment]
@Sleaker, Update 1.6.7 supports 1.13?

**Comment by Lightning11wins** [comment]
Funny, but the latest version of vault I can see is 1.5.6, am I missing something?

**Comment by Sleaker** [comment]
1.7 will be built against the 1.13.1 API.
