### ISSUE TITLE
Cannot get artifact from repository

### ISSUE THREAD

**Issue by Skiftcha** [MilkBowl/Vault#737]
```
<repository>
    <id>vault-repo</id>
    <url>http://nexus.hc.to/content/repositories/pub_releases</url>
</repository>
```
and
```
<dependency>
    <groupId>net.milkbowl.vault</groupId>
    <artifactId>VaultAPI</artifactId>
    <version>1.6</version>
    <scope>provided</scope>
</dependency>
```
results in
`Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Access denied to: http://nexus.hc.to/content/repositories/pub_releases/net/milkbowl/vault/VaultAPI/1.6/VaultAPI-1.6.pom , ReasonPhrase:Forbidden.`

opening link from browser results in Cloudflare page requesting captcha. i can access repository from browser, but maven cannot use browser's cookies and cannot enter captcha.

how can i use it?

**Comment by Sleaker** [comment]
Looks like it's working from my end. it may have been having connectivity issues before. Can you try again?

**Comment by Skiftcha** [comment]
curl http://nexus.hc.to/content/repositories/pub_releases/net/milkbowl/vault/VaultAPI/1.6/VaultAPI-1.6.pom > file.txt

[file.txt](https://github.com/MilkBowl/Vault/files/2358710/file.txt)

**Comment by Sleaker** [comment]
works great. not sure what you're issue is.

**Comment by Sleaker** [comment]
@Skiftcha - this looks like it's an issue between you and cloudflare. The resources uses cloudflare to prevent DDoSing and you may have been blacklisted by cloudflare. I suggest contacting them to see if you have been blacklisted and check if that can be fixed.

**Comment by Skiftcha** [comment]
@Sleaker, i think it is not cloudflare problem, they work correctly **in browser** because i can type captcha and use site.
i just think cloudflare is not intended to be used with maven repositories or other stuff which should be accessed from command line. because maven cannot prove that i am human.

**Comment by Sleaker** [comment]
@Skiftcha I don't get the are you human pop-up, nor do any of the automated services we use. As I mentioned in my above response this could be a result of your IP block getting blacklisted by cloudflare to force you proving you're human anytime you're accessing a resource behind a cloudflare IP.

**Comment by Skiftcha** [comment]
i asked question on cloudflare forum but i think they can not help me.
there is no whitelist features or sudh option in cloudflare
i can not control will or will not cloudflare ask me captcha. it may depend on my country, or subnetwork, or anything else

so putting maven repository behind cloudflare you (or repository ovner) prevent some people from using it. or you force us to use proxies/vpn (which should likely be blocked my cloudflare as well)

**Comment by Sleaker** [comment]
@Skiftcha you can download it manually and install it into your maven cache locally if you need to. no need to use the remote repository. or host your own mirror of the plugin.
