### ISSUE TITLE
VaultAPI: How to add Vault a as a project?

### ISSUE THREAD

**Issue by Lightning11wins** [MilkBowl/Vault#738]
I am having a bit of trouble with the API. **I put the vault.jar in my plugin folder and added "depend: [Vault]" to my plugin.yml**. However, java is not creating any kind of library from the jar (should it?), so all the imports can't be found. **Do I need more than 1 jar to use the vault API?**

**Comment by Pingger** [comment]
you need to add vault.jar as reference to the project in your IDE.
In Eclipse: Open Project Properties, select 'Java Build Path' at the left, select Libraries at the top, select 'Modulepath' in the center. At the right click 'Add External JARs', now select the vault (or vault api) jar

**Comment by Lightning11wins** [comment]
I am using net beans

**Comment by Sleaker** [comment]
@Lightning11wins I have no idea what you're trying to do. Are you making your own plugin? if this is the case you shouldn't be interacting with any of the source from github.

**Comment by Lightning11wins** [comment]
I am just trying to add _vault_ as a project and _vault_ failed! (See above error) Is this a problem with what I did or vault?
