### ISSUE TITLE
Calling Economy#hasAccount results in RuntimeException with Essentials when OfflinePlayer is missing the name

### ISSUE THREAD

**Issue by Phoenix616** [MilkBowl/Vault#746]
When calling [Economy#hasAccount(OfflinePlayer)](https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/economy/Economy.java#L96) when running Essentials as the economy provider can result in a RuntimeException [thrown when the name is null](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/api/Economy.java#L65).

This can happen due to [AbstractEconomy#hasAccount(OfflinePlayer)](https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/economy/AbstractEconomy.java#L20) just using the name of the OfflinePlayer object and passing that to the hasAccount(String) method. The problem is that the Bukkit API might return an OfflinePlayer object that has a null name when using Bukkit#getOfflinePlayer(UUID) in the case that the player is unknown and no name can be found.

One could argue that Essentials should properly catch the case where the name is null when checking for an account but I think that this could as well be handled in Vault directly as this is the one using OfflinePlayer#getName without checking if it's null and Essentials doesn't indicate that this is allowed, maybe the Essentials_Economy class should catch the case where the name is null? (Although that would kinda change the behaviour but I doubt anybody relies on this throwing a RuntimeException as the VaultAPI does not claim that this would happen.

Also here is a stacktrace for this happening that a user of ChestShop [sent me](https://www.spigotmc.org/threads/chestshop.295890/page-5#post-3190044) (although this case should only be happening when a user error setting up the admin shop was made in the plugin so it's not too common): https://pastebin.com/aAADjeda

**Comment by Lightning11wins** [comment]
Maybe you should check to see if the name is null before calling Economy#hasAccount(OfflinePlayer)?

**Comment by Phoenix616** [comment]
Why would a plugin using the API have to test that themselves? The name should not be necessary as players should be identified by their UUID, not a name that could change at any time. If the method accepts an OfflinePlayer object then it has to handle all cases of how that object can be obtained with the Bukkit API. (I mean I'm not talking about a custom OfflinePlayer object that has some unconventional behaviour, this is an object directly gotten by calling Bukkit#getOfflinePlayer(UUID))

**Comment by Lightning11wins** [comment]
Ok... I see. I guess I can't say much because when _I_ tried to use the API, it failed (or I failed, or something.)

**Comment by Phoenix616** [comment]
Seems to be happening with CraftConomy adapter too. Basically the [AbstractEconomy](https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/economy/AbstractEconomy.java#L15) should either check if the username is null or directly use the UUID instead. (Or the individual plugin adapter check if the name is null if the economy plugin does not support null names, using their UUID API would be a lot better though)

**Comment by Wumfie** [comment]
Here's what happened to me. Running two identical servers - one has "Admin Shop" on the signs - works completely fine. I write "Adminshop" (all one word) on the other server and get the same issue in console. Change to "Admin Shop" and works fine again. Strange.

**Comment by Sleaker** [comment]
@Wumfie not really related at all, that's an issue with your shop plugin and how it handles interfacing with accounts itself.

**Comment by Wumfie** [comment]
Wait I think we're talking about different things here

**Comment by BenRulez** [comment]
How do you fix this issue? people cant use adminshops

**Comment by Sleaker** [comment]
'fixed' in latest commit. This is more of a workaround for something that essentials should just make their own adapter to handle.

**Comment by Phoenix616** [comment]
Wouldn't it be better to directly get the UUID from the OfflinePlayer and use the [add(UUID,BigDecimal) method](https://github.com/EssentialsX/Essentials/blob/c9b75aabb219a8d7639c7f0b1b6464ef5ab7d17f/Essentials/src/com/earth2me/essentials/api/Economy.java#L287) instead of falling back to the name?

**Comment by Sleaker** [comment]
@Phoenix616 it most certainly would, those methods didn't exist before and updating the connector to use them would break compatibility with older versions of essentials.  This is why I've mentioned over and over that Plugins now need to provide a maintained connector in their own plugins if they want the best functionality.  All of the connectors that are currently housed in Vault are maintenance only and will not support additional functionality or update for API changes. If a long-running economy plugin changes it's API they are responsible for updating and maintaining a connector.
