### ISSUE TITLE
The "Minecraft" logger is used in some classes

### ISSUE THREAD

**Issue by DoNotSpamPls** [MilkBowl/Vault#748]
Using loggers that aren't the plugin's (for example by using this.getLogger() in the main class) is frowned upon, since it causes a variety of little issues in some cases. Unless it's not required by some restriction or issue, you shouldn't use the Minecraft logger in the API classes.

**Comment by DoNotSpamPls** [comment]
Yes, that's fine, but in some classes the "Minecraft" logger is used instead

**Comment by Sleaker** [comment]
@DoNotSpamPls okay, your initial comment was a bit confusing since it was calling out this.getLogger() as problematic.
