### ISSUE TITLE
Possible Bug?

### ISSUE THREAD

**Issue by DatNubTriz** [MilkBowl/Vault#749]
Using Nodecraft to host my server. Vault's update checker is acting weird?

Console output - https://pastebin.com/hpVUB6ge

On Nodecraft's plugin manager, it gives me the option to update Vault... BUT its telling me to update **FROM** 1.7.1 **TO** 1.6.7?!?!?! 

Something you might wanna look into..?

**Comment by Sleaker** [comment]
This has nothing to do with my plugin, you should contact nodecraft support as they're listing the wrong version to update to.
