### ISSUE TITLE
Spigot 1.12.2 is prompting me to update Vault from 1.5.6 to 1.7.1

### ISSUE THREAD

**Issue by nate2014jatc** [MilkBowl/Vault#750]
Just wondering if the 1.7.1 Version is stable on Spigot 1.12.2, or if any additional testing has been done to this effect.

**Comment by Sleaker** [comment]
it is not. you can ignore the update message if you are sticking to an older version of the server for now. 1.7.1 removes some API functionality that your other plugins may not be ready for if they also require updating to 1.13.x
