### ISSUE TITLE
[Suggestion] Region Support

### ISSUE THREAD

**Issue by ShaneBeee** [MilkBowl/Vault#755]
So one I thing I noticed a lot of devs are having to deal with is region support.
Theres a lot of well know region based plugins (World Guard, GriefPrevention, etc) and even more less known ones. 
The biggest issue devs have to deal with is supporting each region plugin, which can be a lot of work.

EX:
Let's say you made a magic spells plugin. You would most likely want to add region support to prevent players from using spells in a region that does not allow PvP. This could become quite the task with all the random region plugins out there.

The other issue is some of these region plugins change their package names or methods often. World guard is a great example. With that being said plugins are having to update and/or have multiple versions based on different version of Spigot or different versions of said region plugin.

So my suggestion is simple, it would be awesome if you could add a region support system. 
Region based plugins could register their plugin with vault as a region plugin, just like how an economy plugin would register as the economy provider.
Have some methods based around things that could fit into many different region plugins, such as PvP, members (of regions), owners (of regions), flags, etc.
Other plugins would then be able to hook into vault and check for these things, rather than hooking into each and every region plugin out there.

I think that about covers it, Thank you for reading!
- Shane

**Comment by Sleaker** [comment]
See past issue history on this.
