### ISSUE TITLE
Maven repository is unstable

### ISSUE THREAD

**Issue by pavog** [MilkBowl/Vault#756]
http://nexus.hc.to/content/repositories/pub_releases Returns 504 (Gateway Time-out) for a few hours now.

**Comment by tomtoxx** [comment]
I have the same problem, so my Travis build fails. Any chance this'll get fixed in time? 😊

**Comment by pavog** [comment]
Workaround: https://jitpack.io

**Comment by tomtoxx** [comment]
After 2 hours of testing around with jitpack.io I always get a 524 status code back.
Did you have an example that works? If I look at the API of jetpack.io, there are no successful builds.

**Comment by tomtoxx** [comment]
Ok, the only way I get it to work with jitpack is to fork the repository and change the repository for VaultAPI as this will cause the jitpack.io build to fail.

**Comment by tomtoxx** [comment]
https://github.com/MilkBowl/VaultAPI/issues/69

**Comment by Sleaker** [comment]
latest version is available through jitpack.io - https://jitpack.io/#MilkBowl/VaultAPI/1.7 - linking against the released Vault.jar is not supported - you should be linking against only the API.
