### ISSUE TITLE
API-Version not specified in Spigot 1.14.

### ISSUE THREAD

**Issue by Romaq** [MilkBowl/Vault#763]
Log: Server thread/WARN Plugin Vault v1.7.1-b91 does not specify an api-version.

Vault appears to work just fine behind the scenes otherwise for Spigot 1.14.

**Comment by Sleaker** [comment]
Which version of Vault are you trying to run? The last version definitely specifies api-version here: https://github.com/MilkBowl/Vault/blob/master/plugin.yml#L6

**Comment by Romaq** [comment]
And v1.7.1-b91 *is* that version? Yeah, that would be annoying as hell. One of the things I *loved* about Vault is it JUST FACKIN' WORKED across versions even through 1.13. If the API is the ONLY thing you had to touch, that would be a big ball of suck for you. :( I agree. Have you poked MD_5 on this?

**Comment by Sleaker** [comment]
looks like it wasn't included until build 92. so going to close this issue since it's in the current dev version, and it's just a minor cosmetic thing.  It'll be gone when I push 1.7.2.

**Comment by Romaq** [comment]
Cool! Thank'ee. :)
