### ISSUE TITLE
Vault (v1.7.2-b107) - I get little high timings.

### ISSUE THREAD

**Issue by Ethon6** [MilkBowl/Vault#766]
Java 8.0 Paper Spigot 1.14.1 (fully updated)

Report:
![kép](https://user-images.githubusercontent.com/19668243/57998035-e88ec380-7acf-11e9-8fb4-095abdc1258f.png)

![kép](https://user-images.githubusercontent.com/19668243/57998086-24298d80-7ad0-11e9-9a7f-269575e6ba99.png)

**Comment by Sleaker** [comment]
you can turn off metrics, but it's also being run in a separate thread... so not sure why the perf profiler thinks it's taking up any tps.
