### ISSUE TITLE
Command error when using almost anything attempting to take money from a player

### ISSUE THREAD

**Issue by Omni-MC** [MilkBowl/Vault#767]
https://paste.ee/p/UdneF MC Version: 1.7.10, Forge: 10.13.4.1614, Thermos: 1614

This is just an example of trying to use BankNote Advanced. It seems to happen when using AreaShops, haven't tested sign shops yet.

**Comment by Sleaker** [comment]
you didn't list what version of Vault, or what version of Bukkit, so I'm going to assume you're trying to use versions of MC I have never supported.
