### ISSUE TITLE
TRAVIS BUILD NUMBER

### ISSUE THREAD

**Issue by Momonche** [MilkBowl/Vault#770]
Hello !

It's a very useless issue but when I use /ver vault the version is broken

https://i.imgur.com/0cxVXJv.png

**Comment by Sleaker** [comment]
thanks for the report. was this from the version downloaded off the bukkit website or build recently done?

**Comment by Momonche** [comment]
I see that problem on Vault 1.7.2 on SpigotMC

And now I use the dev builds on Jenkins 1.7.3 and the problem stay on

**Comment by Sleaker** [comment]
@Momonche there is no official jenkins for Vault. so you're getting a potentially unsupported version, that's why the build number is not getting set in that version.
