### ISSUE TITLE
Chat Null Setup

### ISSUE THREAD

**Issue by grandmen123** [MilkBowl/Vault#772]
Issue: Chat Setup returns Null

Log: https://pastebin.com/HNFR4qew
Main.java: https://pastebin.com/Kx0UCzCP

When I load up the world and setup chat/permissions/economy I get Perms and Economy setup but chat seems to return null (You can see by the output statement "log.info("Is chat working " + this.setupChat() + "");" line 32.

I'm using the most up to date vault, any idea on why this is happening?

Thanks in advance!

**Comment by montlikadani** [comment]
Yes, because you called twice the ` this.setupChat();` method in your onEnable method.
