### ISSUE TITLE
Multi Currency option. [funding available]

### ISSUE THREAD

**Issue by NullCase** [MilkBowl/Vault#773]
Have you given up on this idea? Because I'm happy to pay you for development work. And to explain why its worth doing, if you like.

How much money would it cost to add multi-currencies?

Here's why this matters to me.

I run Liberty Minecraft. We're building an argument that economics can be tested in video games. At least, that's a goal.

The option to have more than one currency lets me demonstrate what happens when people use fractional reserves. How this impacts the economy... It lets players decide what type of money is the best for them. Stuff like this.

-------------

It seems like there's a few ways to implement multi currencies. I'd like to try and describe one way here.

1) Add four (or so) currency symbols to Vault where each one can hold it's own balance.

So players can have a $ balance, €, £, ¥ balances.

2) I would work to develop something in ChestShop so that currency types can be selected when creating a shop. I've worked with Phoenix616 a little, but if necessary we'd fork the project.

3) There's going to be challenges, but I'm prepared to work through that.

What's the biggest challenge you're working on rn with Vault?

**Comment by Sleaker** [comment]
The answer to this question still is to just hook directly into the economy you want to use that supports it (there aren't very many iirc).

**Comment by Lightning11wins** [comment]
Just an unrelated side comment, are you one of the owners of the Liberty Creative server? You said 
> I run Liberty Minecraft.
Does that mean a type of Minecraft or a specific server?

**Comment by NullCase** [comment]
hi @Lightning11wins Liberty Creative server is someone else. 

This is LMC. https://www.libertyminecraft.com/

**Comment by NullCase** [comment]
@Sleaker it sounds like forcing that update into Vault would cause a lot of headache for plugin developers.

**Comment by Lightning11wins** [comment]
Ok, the guy who runs Liberty Creative is named Bob anyway.
Your server looks really cool, though. I hope I can check it out sometime.
Now I will shut up and stop pulling this thread into a rabbit hole!
I hope the multicurrency idea goes well! Thanks for suggesting it, I never even thought of that!
