### ISSUE TITLE
Suggestion: option to log every success economic transaction.

### ISSUE THREAD

**Issue by ArtNRG** [MilkBowl/Vault#774]
There are a lot of plugins on servers that use economy features using the vault. It will be really comfortable to have the main transaction log in one place. /pay, /trade, auction house, chest shop, boss shop and a lot of other ways to spend money are making the administrator dig through lots of logs to answer player where he lost/spend his money. This situation is appearing not so often but it really tricky if you need to find something like that. 
So my suggestion is to log timestamp, the plugin name, and the player nickname with money amount after every economy transaction. It also can be used to monitor the economic situation on the server like comparing the server summary income and spendings. 
This feature can be optional with the ability to turn it on or off in the configuration file. 
Thank you in advance!

**Comment by Lightning11wins** [comment]
Sounds like a great idea!! I can't do anything to make it happen, but I hope someone who can dose!

**Comment by Sleaker** [comment]
this would have to be implemented at every connector, it's not an ideal thing to have. The better option is to just use an economy implementation that logs everything.
