### ISSUE TITLE
Error when users log in

### ISSUE THREAD

**Issue by MajorGoodHeart** [MilkBowl/Vault#775]
Get the following error when a player joins.  using 1.13.2 Spigot.  Vault was updated but not fixing the issue.

[WARNING] Error occurred while fetching a player's groups from Vault.
[ERROR] Exception Caught:
java.lang.NullPointerException: null

**Comment by Sleaker** [comment]
I would need more of the error log to tell if this is an actual issue in Vault, or if another plugin is doing things incorrectly.  This seems like a plugin error though, not an issue in Vault.
