### ISSUE TITLE
Auto-tab-complete not work in world edit if you have admin permissions 

### ISSUE THREAD

**Issue by broken1arrow** [MilkBowl/Vault#776]
Hi, auto-tab-complete not work in world edit if you have admin permissions on spigot and paper 1.14.4, only work if you are OP.

**Comment by Sleaker** [comment]
I'm not really interested in trying to patch this feature as it's pretty low-impact.

**Comment by broken1arrow** [comment]
Hi, thanks for replay. 

I got more info, from world edits dc and looks like you have done som error with permissions. 
 

Some way your pluggin takes over, admin get red text when typing world edit command. Is way op permission work and not admin. 

I can see if I can get more info to you.
