### ISSUE TITLE
" workaround" Auto-tab-complete not work in world edit if you have admin permissions

### ISSUE THREAD

**Issue by broken1arrow** [MilkBowl/Vault#777]
I get a solve the problem with " workaround" , on server we change wepif.yml file. 

And put in this string
```
disabled:
 - VaultResolver
```

So is your permission interfere with world edit, so what I understand so think the server admins not have permissions (so you get red text=you don´t have permissions, but the command work ether way).

New info from my last thread

I got more info, from world edits dc and looks like you have done som error with permissions.

Some way your pluggin takes over, admin get red text when typing world edit command. Is way op permission work and not admin.

I can see if I can get more info to you.

**Comment by Sleaker** [comment]
All that does is turn off worldedit registering itself into the permissions API of Vault. If that's the 'fix' then just disable it. It has nothing to do with Vault interfering.
