### ISSUE TITLE
Mobs dont attack

### ISSUE THREAD

**Issue by gmanc2** [MilkBowl/Vault#780]
When Vault is added to a server running 1.14.4 the mobs do not attack players and occasionally lose their AI.

**Comment by montlikadani** [comment]
This plugin absolutely don't doing anything with entities. Also, if you added this plugin, make sure you configured something incorrectly in "entity managing" plugin configuration.

**Comment by gmanc2** [comment]
I made sure it was this plugin, I ran it fresh install without any other plugins and only this caused it.

**Comment by montlikadani** [comment]
Check in essentialsProtect.

**Comment by Lightning11wins** [comment]
Are you sure?

*Thank You*,
Israel *R.* Fuller

<Lightning_11>* I win!*
