### ISSUE TITLE
Recommendation Bukkit scope to provided instead of default compile

### ISSUE THREAD

**Issue by yannicklamprecht** [MilkBowl/Vault#786]
https://github.com/MilkBowl/Vault/blob/master/pom.xml#L75-L79

**Comment by FelixKlauke** [comment]
Bukkit shouldn't be shaded into the jar, as a custom artifact set is provided (https://github.com/MilkBowl/Vault/blob/master/pom.xml#L446-L451). If you package vault it shouldn't contain bukkit.

The `shade` goal is working as expected:
```
[INFO] --- maven-shade-plugin:3.1.0:shade (default) @ Vault ---
[INFO] Excluding org.bukkit:bukkit:jar:1.13.1-R0.1-SNAPSHOT from the shaded jar.
[INFO] Excluding commons-lang:commons-lang:jar:2.6 from the shaded jar.
[INFO] Excluding com.googlecode.json-simple:json-simple:jar:1.1.1 from the shaded jar.
[INFO] Excluding junit:junit:jar:4.10 from the shaded jar.
[INFO] Excluding org.hamcrest:hamcrest-core:jar:1.1 from the shaded jar.
[INFO] Excluding com.google.guava:guava:jar:21.0 from the shaded jar.
[INFO] Excluding com.google.code.gson:gson:jar:2.8.0 from the shaded jar.
[INFO] Excluding org.yaml:snakeyaml:jar:1.21 from the shaded jar.
[INFO] Including net.milkbowl.vault:VaultAPI:jar:1.7 in the shaded jar.
[INFO] Including org.bstats:bstats-bukkit:jar:1.5 in the shaded jar.
[INFO] Excluding com.greatmancode:craftconomy3:jar:3.2.2-SNAPSHOT from the shaded jar.
[INFO] Excluding com.greatmancode:tools:jar:1.3-SNAPSHOT from the shaded jar.
[INFO] Excluding org.xerial:sqlite-jdbc:jar:3.7.15-M1 from the shaded jar.
[INFO] Excluding org.slf4j:slf4j-api:jar:1.7.12 from the shaded jar.
[INFO] Excluding com.zaxxer:HikariCP-java6:jar:2.3.7 from the shaded jar.
[INFO] Excluding org.javassist:javassist:jar:3.18.2-GA from the shaded jar.
[INFO] Excluding com.h2database:h2:jar:1.4.187 from the shaded jar.
[INFO] Excluding org.projectlombok:lombok:jar:1.12.6 from the shaded jar.
[INFO] Replacing original artifact with shaded artifact.
```

Can you add some steps to reproduce or give some more proof?

**Comment by yannicklamprecht** [comment]
https://www.spigotmc.org/threads/player-spigot-does-not-exist.406974/#post-3621773

**Comment by FelixKlauke** [comment]
The you're just wrong here. This is the repository for the vault implementation, you're searching for the API. You can find the corresponding repo here: https://github.com/MilkBowl/VaultAPI :D

**Comment by yannicklamprecht** [comment]
I would be very happy if you could transfer this issues to the VaultAPI project.

**Comment by FelixKlauke** [comment]
I'm sadly not a maintainer. @Sleaker will have to do this for you.

**Comment by Sleaker** [comment]
github doesn't have a 'transfer issue' command like that. also I'm not sure what you're reporting here.

**Comment by FelixKlauke** [comment]
@Sleaker In fact it has, brand new.
<img width="277" alt="Bildschirmfoto 2019-12-14 um 07 40 05" src="https://user-images.githubusercontent.com/16369612/70844706-072a2280-1e45-11ea-9004-34ded445f781.png">
At the bottom you have a button for transferring issues. 

His problem is described here: https://www.spigotmc.org/threads/player-spigot-does-not-exist.406974/#post-3621773

It seems like he would have a problem with the exposed bukkit api.

**Comment by Sleaker** [comment]
@FelixKlauke - vault doesn't use any of the 'brand' features so that doesn't work for this project.
