### ISSUE TITLE
register economy

### ISSUE THREAD

**Issue by meerpaluten** [MilkBowl/Vault#788]
methode:   private boolean setupEconomy() {
      if (getServer().getPluginManager().getPlugin("Vault") == null) {
          return false;
      }
      RegisteredServiceProvider<Economy> rsp = getServer().getServicesManager().getRegistration(Economy.class);
      if (rsp == null) {
          return false;
      }

      econ = rsp.getProvider();
      return econ != null;
  }
rsp is null. how else am I supposed to do that

**Comment by Sleaker** [comment]
make sure you're installing an economy plugin on the server too..
