### ISSUE TITLE
Missing dependency declaration

### ISSUE THREAD

**Issue by SlimeDog** [MilkBowl/Vault#789]
Spigot 1.15.2 (Jenkins 2596)
Vault 1.7.3-b18

**Description**
Beginning with Spigot 1.15.2 (Jenkins 2596), missing dependency declarations are reported in the log on server start-up as WARN messages.

Reference: [https://hub.spigotmc.org/jira/browse/SPIGOT-5546](https://hub.spigotmc.org/jira/browse/SPIGOT-5546)

The relevant log entry is:
```
[22:03:03] [Server thread/WARN]: [Vault] Loaded class com.earth2me.essentials.api.Economy from Essentials v2.17.1.53 which is not a depend, softdepend or loadbefore of this plugin.
```

**Steps to reproduce the behavior**
- Update Spigot to 1.15.2 latest
- Start the server
- Search the log for 'Loaded class'

**Expected behavior**
Dependencies should be declared in plugin.yml

**Comment by andrewkm** [comment]
Same here.

`[20:00:48] [Server thread/WARN]: [Vault] Loaded class com.earth2me.essentials.api.Economy from Essentials vEcoCityCraft which is not a depend, softdepend or loadbefore of this plugin.
`

**Comment by Sleaker** [comment]
soft-warning seems fine in this case. we don't want to add a softdep on essentials as we don't want it to force-load first.
The way Vault performs it's detection is that it checks if the class exists before the loader has a chance to load them, but this is fine.. see: https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/Vault.java#L541

Vault will generate warnings on every plugin that hasn't built it's own connector, this is just another reason why I've pushed econ maintainers to write their own connectors.
