### ISSUE TITLE
iConomy 7 + vault 1.7.2 - Iconomy doenst work.

### ISSUE THREAD

**Issue by NikolaiCinotti** [MilkBowl/Vault#795]
Heres the log:

`Time elapsed: 1006 ms
18.02 18:11:45 [Server] Server thread/INFO [iConomy] Enabling iConomy v7.0
18.02 18:11:45 [Server] Server thread/ERROR Error occurred while enabling iConomy v7.0 (Is it up to date?)
18.02 18:11:45 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.Server.getServerName()Ljava/lang/String;
18.02 18:11:45 [Server] INFO at com.iCo6.iConomy.onEnable(iConomy.java:101) ~[?:?]
18.02 18:11:45 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
18.02 18:11:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
18.02 18:11:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
18.02 18:11:45 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
18.02 18:11:45 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
18.02 18:11:45 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
18.02 18:11:45 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
18.02 18:11:45 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
18.02 18:11:45 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
18.02 18:11:45 [Server] Server thread/INFO [Vault] [Vault][Economy] iConomy 7 hooked.`

any help?

**Comment by Fadest** [comment]
That plugin didn't stop being updated since 2015? Anyway, the error is from iConomy, not Vault.
