### ISSUE TITLE
Request to add two constructors to make MockBukkit compatible

### ISSUE THREAD

**Issue by Markyroson** [MilkBowl/Vault#799]
Could Vault.java please have these two constructors added? They allow [MockBukkit](https://github.com/seeseemelk/MockBukkit) to work and load the plugin as a dependency for others that you wish to test. In my case, I have Vault as a dependency for my plugin that I would like to test with MockBukkit.

```
public Vault()
    {
        super();
    }

    protected Vault(JavaPluginLoader loader, PluginDescriptionFile description, File dataFolder, File file)
    {
        super(loader, description, dataFolder, file);
    }
```

Thank you for your time and for considering this. Thanks!

**Comment by Sleaker** [comment]
MockBukkit should be made compatible with the built-in ways bukkit plugins are constructed, not force plugins to be made compatible with it.
