### ISSUE TITLE
Consider uploading plugin jar to Github releases

### ISSUE THREAD

**Issue by mikroskeem** [MilkBowl/Vault#801]
Mainly because neither Spigot or Bukkit provide direct download links for the plugin, making automation less convenient.

Also looked for alternatives - Spiget does not seem to even recognize the Vault project and Bukget is long gone by now. Seems like Travis CI is pushing Vault to nexus.hc.to, but how reliable is it?

**Comment by Sleaker** [comment]
@mikroskeem as I mentioned earlier. Vault is not available as a maven release because it's for *server* operation only. It's not for use in builds.

**Comment by mikroskeem** [comment]
>It's not for use in builds.

I think you misunderstood me. I'm working on a solution which allows basically one click server creation, that involves downloading plugins from the internet. I'm not building code against Vault plugin itself (which would be pretty dumb indeed) :smile:

**Comment by Sleaker** [comment]
See: https://www.curseforge.com/minecraft/bukkit-plugins/vault - or https://www.spigotmc.org/resources/vault.34315/

**Comment by Sleaker** [comment]
Vault has an updater builtin that uses bukkit's builtin rss feeds to know when there's a new version available. Just use that to get the latest download link.

**Comment by mikroskeem** [comment]
As mentioned before, then neither Spigot or Bukkit provide direct download links, thus unusable with e.g `curl`... But whatever, I'll consider alternative solutions then. Thanks for your time.
