### ISSUE TITLE
Essentials MaxMoneyException is not implemented

### ISSUE THREAD

**Issue by mastercake10** [MilkBowl/Vault#805]
Apparently, EssentialsX offers a config option that lets you define a `max-money` amount. Essentials itself includes a `MaxMoneyException`, which is used when depositing money via the /pay command, while the [Vault implementation](https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/economy/plugins/Economy_Essentials.java#L151) doesn't handle this Exception at all.

This leads to money loss, since calling the `Economy#depositePlayer` method always returns SUCCESS, even when reaching the money limit.

**Comment by mastercake10** [comment]
I just tried to fix it on my own, but I figured out that there are two, inconsistent implementations. The [Economy API](https://github.com/EssentialsX/Essentials/blob/d7b0f74a75b26722abca402eaef92a0a0e06af06/Essentials/src/com/earth2me/essentials/api/Economy.java#L110) of Essentials - which Vault is using - doesn't implement the MaxMoneyException yet, however, the [Essentials User class](https://github.com/EssentialsX/Essentials/blob/d7b0f74a75b26722abca402eaef92a0a0e06af06/Essentials/src/com/earth2me/essentials/User.java#L365) does.

I am uncertain if this issue should be solved by using this User class, or by updating the Economy API on Essential's end. The first option wouldn't break backward compatibility that much.

**Comment by Sleaker** [comment]
This is another one of those reasons why I suggest economies implement their own interface. the current essentials adapter is a legacy product and no longer maintained. if it works, then great. if it doesn't then essentials needs to provide a better working alternative.
