### ISSUE TITLE
Error when selling something in Admin Shop

### ISSUE THREAD

**Issue by MauriceLPs** [MilkBowl/Vault#806]
Dear developers,

I developed an own moneysystem (with database) and wanted to do that with Vault.
Buying something from AdminShop is working very good and doesn't even throw any fails (and also removes the money properly.

But vice-versa it doesn't work. Even with other Items (and/or with User Chests).

I am getting this error: https://pastebin.com/kCJfpd4n
That's my Vault-Code in my plugin: https://pastebin.com/82FWm8dM
If you want my source code with the setmoney, addmoney, etc. commands and the methods using in Vault-Code, tell me and I will upload it also.

Also everything is working fine, except selling.

I also tried to user a version below the 1.15.2 release, used different Vault-Versions, nothing worked, I always getting this UUID (what even doesn't exists)

Greets,
Maurice Bailey

**Comment by Sleaker** [comment]
Well the stack trace doesn't match the posted code. So I'm not really able to help you there. If you're using your own economy, make sure you're not using AbstractEconomy. Use the interface and implement everything. Also specifically make sure you have an actual player before you start performing operations. Some economies need the user to have a name, not just a raw offlineplayer object.

**Comment by MauriceLPs** [comment]
I also checked now the Economy Plugin, I have used until I wroten mine.
The Error also appears on BConomy. It always wants to set money to a UUID what doesn't even exists.

Error: https://prnt.sc/sp0rx9
