### ISSUE TITLE
CHUNK placeholder VAULT lags

### ISSUE THREAD

**Issue by Bricec6** [MilkBowl/Vault#807]
Hello I noticed that I had lags on my server, after several tests etc, I noticed that the placeholders of vault economy(see photo) repeat every x seconds create peaks of tps on the servers because it makes bug the complete chunk.
![image](https://user-images.githubusercontent.com/51750055/83514195-73700f80-a4d3-11ea-8f42-60b2021dce87.png)

the check pauses and then resumes (see config), which causes tps peaks
![image](https://user-images.githubusercontent.com/51750055/83514351-c649c700-a4d3-11ea-81db-64f82c801f32.png)

if I move away from this placeholder, for example I put myself on a par chunk, the place where it was before doesn't create peaks anymore, but the new place where I will create peaks of tps

i use Holographics Display and HolographicExtensions(for placeholder)

config:
![image](https://user-images.githubusercontent.com/51750055/83514237-8aaefd00-a4d3-11ea-9316-05630c410943.png)

it should be known that only vault causes this problem the other permanent check plugins like bentobox or dkcoins do not cause this kind of problem.

I reported that bug to holographics extensions, too . I reported that bug to vault, too .https://github.com/Niall7459/HolographicExtension/issues/34
thank you!

**Comment by Niall7459** [comment]
This most likely isn't a Vault issue. I don't see why holographic extension would cause a noticeable TPS increase either. The bal top placeholders are calculated asynchronously. If you could do a timings report that would help.

Thanks.

**Comment by Sleaker** [comment]
Closed per @Niall7459 comment. Completely unrelated to Vault.
