### ISSUE TITLE
General Stacking API

### ISSUE THREAD

**Issue by BONNe** [MilkBowl/Vault#809]
Vault offers Economy and Permission API that allowed very easy different plugin integration and saved a lot of time for developing and supporting these functions in our plugins.
But it looks like, Vault could offer one more useful API, for developers and server owners: General Stacking API.

Currently, in Bukkit based plugins we are running into an overflow with different plugins that supports block and entity stacking. Each of the uses their own API and it becomes very time costly to find all their different implementations and implementing them in your own plugin. 

So I would suggest creating a general stacking API like it is with Economy API. This would allow generalizing all these different block/entity stacking plugins and would save a lot of time with implementing any functions that would like to check for stacked blocks/entities.

**Comment by Sleaker** [comment]
Vault isn't about adding new APIs anymore. As others have suggested  a lot of different things to be added my suggestion is for you to just make it yourself in the same way that Vault handles the others if you think it will be helpful!
