### ISSUE TITLE
1.16.x Support?

### ISSUE THREAD

**Issue by srnyx** [MilkBowl/Vault#812]
Does the plugin work on 1.16.x?

**Comment by Dnaleor77** [comment]
yes... I also downloaded the 1.7.3 beta, which also seem to work fine

**Comment by srnyx** [comment]
> yes... I also downloaded the 1.7.3 beta, which also seem to work fine

Where can I find the beta downloads?

**Comment by Dnaleor77** [comment]
> > yes... I also downloaded the 1.7.3 beta, which also seem to work fine
> 
> Where can I find the beta downloads?

Uhm... I googled, think it was on Jenkins. But it's not the stable build. 1.7.2 runs just fine.
