### ISSUE TITLE
My vault is in conflict with LegendChat

### ISSUE THREAD

**Issue by MarcusRai** [MilkBowl/Vault#813]
My vault is in conflict with LegendChat, because when I remove the vault the lc works normally,
already deletes the Chat folder from the vault, and still the error continues, PLS HELP !!!!!!

**Comment by Sleaker** [comment]
Vault is an API that allows other plugins to access a shared interface, it doesn't have active code that will conflict or break other plugins in the manner you suggested. If removing Vault causes something to start working then one of your other plugins you have installed is doing something incorrectly with it.
