### ISSUE TITLE
Vault v1.7.3-b131 not depend, softdepend or loadbefore of this plugin

### ISSUE THREAD

**Issue by Bloodlex** [MilkBowl/Vault#820]
Hey, I don't know if it belongs here or to PlaceholderAPI but I get such a warning:

09.08 08:31:03 [Server] WARN [PlaceholderAPI] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 which is not a depend, softdepend or loadbefore of this plugin.

Please tell if I should contact Placeholder API for that. I have no idea what that is supposed to mean.

**Comment by Sleaker** [comment]
you can ignore this warning.
