### ISSUE TITLE
Items class disappeared when I updated Vault

### ISSUE THREAD

**Issue by reesercollins** [MilkBowl/Vault#821]
Despite https://milkbowl.github.io/VaultAPI/net/milkbowl/vault/item/Items.html still being a valid page, the entire item package was removed in vault and I don't see any sort of replacement. I looked at GitHub commits and I don't see it ever existing. Perhaps I'm going crazy, but I seriously hope not.

**Comment by Sleaker** [comment]
It was removed because the whole interface was deprecated back when minecraft removed the material API and started using tags much more heavily. unfortunately my automated script doesn't seem to have removed the API reference page though.
