### ISSUE TITLE
Players Unable to do /bal or related commands even with permissions

### ISSUE THREAD

**Issue by Sl1pstr3am** [MilkBowl/Vault#826]
Hi! So I'll admit, I'm a little new to server hosting. I host a small PVP server for my friends and I to play on. I wanted to add some economy plugins that way when we get kills, we get a certain amount of money. I'm using an ancient plugin to do the kill rewards, but it seems to work. However, my players who aren't operators don't seem to have access to the /bal commands, which is an issue. I even tried giving them the permission for vault admin, but that didn't work either. 
I'm using groupmanager for the permissions. Any help is appreciated!
I've attached a screenshot of the plugins I'm using, as well as the permissions I've allocated in the groupmanager config. Thanks in advance!
![ss1](https://user-images.githubusercontent.com/71157650/92980692-d2dba500-f45c-11ea-9eb0-476c823b82f2.PNG)
![ss2](https://user-images.githubusercontent.com/71157650/92980697-d66f2c00-f45c-11ea-844c-c5d724383709.png)

**Comment by Sleaker** [comment]
Vault doesn't provide an economy itself nor does it provide a balance command, the vault.admin permission is for doing economy conversions and to get notices on updates. You'll need to check with whatever economy plugin you're using on how to operate it. such as essentials.
