### ISSUE TITLE
Placeholder "vault_prefix_color" & "vault_suffix_color" do not support hex color codes

### ISSUE THREAD

**Issue by Butterness01** [MilkBowl/Vault#828]
Whenever using the placeholder `vault_prefix_color` or `vault_suffix_color` it returns the last color code in a hex color code such as `&x&f&f&4&2&3&f` (this would return `&f` since it's the last color code).

**Comment by Sleaker** [comment]
not sure what you're doing here. Vault doesn't use any tags it's a programmatic API.

**Comment by Butterness01** [comment]
Sorry, got confused with PlaceholderAPI having a Vault placeholder extention.
