### ISSUE TITLE
Vault causes garbage in the logs

### ISSUE THREAD

**Issue by WINGS07** [MilkBowl/Vault#832]
Installed plugins:
`[14:02:47] [Server thread/INFO]: Plugins (37): AdvancedBan*, AmkMcAuth, AntiVPN, AutoMessage*, CmdSpy*, CoreProtect, CreeperControl*, Essentials, EssentialsChat, Geyser-Spigot, HideStream*, JDLogger*, LibsDisguises, LuckPerms, MOTD, MultiWorld*, Negativity, PlayTimeTracker, PluginHiderPlus*, PlugMan, ProtocolLib, ProtocolSupport, ProtocolSupportStuff, ProtocolSupportUpdater*, SimpleSit*, SkinsRestorer, Sudo*, SuperVanish, TAB, TelegramBotsAPIPlugin*, TGConsole*, TrollBoss, VANILLA_VANISH, Vault, ViaVersion, WorldBorder, WorldEdit`

If Vault installed:
`[13:57:43] [Server thread/INFO]: Send: [CoreProtect] WorldEdit logging successfully initialized.
[13:57:43] [Server thread/INFO]: [CoreProtect] WorldEdit logging successfully initialized.`

If vault not installed:
`[14:01:29] [Server thread/INFO]: [CoreProtect] WorldEdit logging successfully initialized.`

_and so not only with CoreProtect_

_mostly with plugins using Bukkit.getLogger()_

Paper 1.16.4
Latest vault from SpigotMC

**Comment by Sleaker** [comment]
This was already cleaned up over a year ago: #748
