### ISSUE TITLE
Glitch on Vault placeholders when value is "0.001"

### ISSUE THREAD

**Issue by Tomi010817** [MilkBowl/Vault#833]
### Installed plugins: (3)
`EssentialsX-2.18.2.0`
 `PlaceholderAPI-2.10.10-DEV-110`
 `Vault-1.7.3`

### Environment:
Spigot 1.8.8

### Description:
When you set yourself the amount "0.001" of money, it will display as "9.999999999999998E-4" when you parse the placeholder `%vault_eco_balance%`. Though the amount of money displays well when slashing "/money [name]".
https://i.imgur.com/eOBbhDS.png

### How to reproduce:
1- Download Vault's PlaceholderAPI expansion.
2- Set your balance exactly to "0.001", with `/eco set [Yourname] 0.001`
3- Slash "/papi parse me %vault_eco_balance%"

**Comment by Sleaker** [comment]
none of this is related to vault.

**Comment by Tomi010817** [comment]
Thank you!
