### ISSUE TITLE
Version displays incorrect build value

### ISSUE THREAD

**Issue by SlimeDog** [MilkBowl/Vault#837]
Vault version 1.7.3-b21
```
> version Vault
[13:34:59 INFO]: Vault version 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
```

**Comment by Sleaker** [comment]
This means you're not running an official version. I don't support unofficial builds. The correct place to download Vault is from the project page on curseforge.com or spigotmc.org

**Comment by SlimeDog** [comment]
What about https://ci.md-5.net/job/Vault/ dev releases?

**Comment by Sleaker** [comment]
@SlimeDog that is not my build server. I do not do dev releases.  You're trusting whoever runs that server (caveat, probably fine). What I referenced above are the only 3 official download locations that I manage.

**Comment by SlimeDog** [comment]
OK. Thanks.
