### ISSUE TITLE
what perm plugins are at 1.16.4 are available?

### ISSUE THREAD

**Issue by Bumshifu** [MilkBowl/Vault#841]
what perm plugins are at 1.16.4 are available?

**Comment by Geolykt** [comment]
Luckperms is the most known and pretty much the only recomended plugin out there, although feel free to prove me wrong.
BPerms 1 (2.0 is not out yet) should not be used, even if it is the most recommended plugin by threads from 2016

**Comment by Bumshifu** [comment]
where can i get the 1.16.4 version?

**Comment by Geolykt** [comment]
https://luckperms.net/download
