### ISSUE TITLE
Vault Spawners Disabled

### ISSUE THREAD

**Issue by redhatboy1** [MilkBowl/Vault#842]
Hi I have vault on my 1.16.4 server. When I try to place spawners I get given an error saying; 'Placement of spawners has been temporarily disabled!'

I have narrowed it down to Vault by setting up a duplicate server and slowly deleting the plugins until it works and Vault is when it flips. Just to make sure its not anything else I have tried it with everything but vault and it works fine. Though the second I add vault back it gives me that error when I try to place spawners.

**Comment by Sleaker** [comment]
You have a plugin that enables some functionality which breaks your server when vault is installed. Vault is a passive plugin and doesn't do anything related to spawners.
