### ISSUE TITLE
Vault and Luckperms 

### ISSUE THREAD

**Issue by Dimitryyyy** [MilkBowl/Vault#844]
Hello! I have a server, in spigot 1.8.8. And then i downloaded the new update, and now in the scoreboard the ranks doesnt work. Here is a photo, and the economy is working, but the ranks doesnt. [https://i.imgur.com/KVuP3TA.png](url)

**Comment by Dimitryyyy** [comment]
Console:
at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:223)
at com.extendedclip.papi.expansion.vault.BalTopTask.run(BalTopTask.java:52)

**Comment by Sleaker** [comment]
this is an issue in VaultEcoHook or BalTopTask I don't know what plugin is causing it, but this is not a Vault issue.
