### ISSUE TITLE
Placeholders on deluxemenu

### ISSUE THREAD

**Issue by uLyPANNN** [MilkBowl/Vault#847]
Hello, I have a problem with the vault placeholders, it does not display the top players in the deluxemenu menu.

configuration: https://prnt.sc/105q64d 

display: 
![image](https://user-images.githubusercontent.com/63079517/109016830-3bdb7000-76bf-11eb-8537-103e3732fc6a.png)

baltop: 
![image](https://user-images.githubusercontent.com/63079517/109016968-61687980-76bf-11eb-8c02-09f5f1a3fe3b.png) 

version vault: 
![image](https://user-images.githubusercontent.com/63079517/109016999-6a594b00-76bf-11eb-9fb2-f5ea3decd95b.png)

server jar: paper 1.16.5

**Comment by Geolykt** [comment]
Vault is, as far as I know, not responsible for place-holders, I would inform the plug-in implementing the place-holders about this issue

**Comment by Sleaker** [comment]
@uLyPANNN this is definitely not a Vault thing.
