### ISSUE TITLE
Vault-Conversion Not Working

### ISSUE THREAD

**Issue by Miroluvswii** [MilkBowl/Vault#848]
I’m currently having issues migrating my server's economy with vault-convert. I attempted to convert from lighteconomy to TheNewEconomy. When I ran the command it seemed to run fine saying the conversion had completed and there were no errors in the console, but none of the data had changed. 

What I get: http://gyazo.com/5a169226409d830086a7d4d9b1be8123

**Comment by Sleaker** [comment]
@Miroluvswii the conversion tool is provided as-is. I can't really help without more explicit information on what you're seeing missing. You'll need to actually look at the data where it's stored to verify what happened.
