### ISSUE TITLE
vault Expand

### ISSUE THREAD

**Issue by 157946a** [MilkBowl/Vault#851]
May I ask when will the vault extension be updated to be compatible with the new version of papi?

**Comment by 157946a** [comment]
%vault_eco_top_balance_#%
%vault_eco_top_balance_fixed_#%
%vault_eco_top_balance_formatted_#%
%vault_eco_top_balance_commas_#%
%vault_eco_top_player_#%
%vault_eco_top_rank%
These variables are all returned to 0, is there something wrong?

**Comment by Sleaker** [comment]
@157946a - this has nothing to do with vault. check with the plugin that provides them.

**Comment by 157946a** [comment]
I used the essentials plugin, I don't know what's going on, is there a difference between essX and ess

**Comment by Geolykt** [comment]
Ess - unmaintained and only supports 1.7.10
EssX - the one you should be using

**Comment by 157946a** [comment]
That's weird, I used essX, but she still returns 0, papi, vault, vault extension, essX is the latest version, but still returns 0

**Comment by Geolykt** [comment]
EssX should not provide the placeholders, if it does, open an issue there if there is none already.
The issue should be at the vault extension however, don't ask me why it is outdated however, the vault API hasn't changed in months (maybe even years)

**Comment by 157946a** [comment]
Is it possible to fix this problem?

**Comment by Geolykt** [comment]
no real idea
