### ISSUE TITLE
Might be a little information may it helps for 1.17.1

### ISSUE THREAD

**Issue by CloudeLecaw** [MilkBowl/Vault#855]
Hello

Today did the firsts tests with some offline server i created to see what might may could went wrong before we might thing about switching to the new version.

Sadly we noticed that Vault is loading but plugins seem dont to find Vault anymore.
i dont know if this is the reason of Vault or the plugins.

so i got meassages like:
```
Vehicles >> Vault Economy not found, disabling shop.
Failed to hook Vault!
[BuyRentRegion] No Vault-compatible economy plugin found!
```

Well i just saw 3 plugins for now behaving like it. so i will inform these devs too that their plugins have not found vault in
1.17.1 (Vault 1.7.3 - Build 131)

Pls just take this as an information - it might does not is vaults fault as the otehr plugins seem to hook fine.

**Comment by Geolykt** [comment]
Could it be that the economy plugin is not working?

**Comment by CloudeLecaw** [comment]
It could be i will take a look. Oh your right...so just the Informationen of the plugins it would be no vault is incorecct.
