### ISSUE TITLE
Top Balance Placeholders Don't Work

### ISSUE THREAD

**Issue by Reese14** [MilkBowl/Vault#861]
The placeholders that involve top balances (such as %vault_eco_top_balance_commas_#% and %vault_eco_top_player_#%) are not showing anything. It outputs 0.0, and when they are on a hologram it just outputs nothing.

Can show proof if needed

Server Version: Paper-783 (MC: 1.16.5)
Vault Version: Vault v1.7.3-b131
EssentialsX version: 2.18.2.0

**Comment by Geolykt** [comment]
This repository is for Vault proper, since Vault does not implement these placeholders it is up to the plugin implementing these placeholders to resolve this issue

**Comment by Reese14** [comment]
I get what you are saying, but all plugins that are 'implementing' the placeholders are outputting 0.0 or nothing at all.

**Comment by Geolykt** [comment]
Are you sure that your economy plugin is functional?

**Comment by Reese14** [comment]
Yes, the economy plugin is Essentials.

**Comment by Reese14** [comment]
Yes, I did that.

**Comment by lokka30** [comment]
I recommend asking the PAPI team if this issue is caused by PAPI.

**Comment by Reese14** [comment]
Well I don't think it's PAPI, because all other placeholders work.

**Comment by Reese14** [comment]
#851 The issue explained here seems to be the same that I am experiencing. Why did you close the thread without fixing it or helping though?

**Comment by lokka30** [comment]
Vault has zero baltop functionality so please check with the PAPI developers who added the placeholder in

**Comment by Reese14** [comment]
So then what is the placeholder, '%vault_eco_top_balance_#' for? Vault is what displays the baltop functionality.

**Comment by Geolykt** [comment]
Again, Vault does not provide the placeholder nor does it provide the required API for this action. Contact the maintainer(s) of your economy plugin about this

**Comment by Reese14** [comment]
"Vault does not provide the placeholder..."
You do realize '%vault_eco_top_balance_#%' is a Vault placeholder, right?

Also, "Contact the maintainer(s) of your economy plugin about this."
The economy plugin is EssentialsX. It is not an Essentials issue because the player's balance is outputted when using '%vault_eco_balance%', so it has something to do with these specific 'baltop' placeholders; '%vault_eco_top_balance_#%, %vault_eco_top_balance_fixed_#%, %vault_eco_top_balance_formatted_#%, %vault_eco_top_balance_commas_#%, and %vault_eco_top_player_#%,' as they output either '0.0' or nothing at all and is just a blank space.

And before someone says, "Talk to PlaceholderAPI because its a PAPI issue,' you cannot contact or post an issue on PAPI's github regarding an expansion of PAPI. The only issues you can report are PlaceholderAPI plugin-specific issues. If someone else has posted about this issue, don't you all think it should atleast be looked into a little further, or atleast try to recreate the problem to help me and others troubleshoot what the issue is?

I am not trying to be rude about this either, it just seems as if you all aren't really taking this seriously or acting like it's an actual problem.

**Comment by Geolykt** [comment]
Vault has 0 API that allows to obtain the "rank" of a player's balance / baltop functionality.
This means that the placeholder provider (**WHICH IS NOT VAULT**) has to individually add this functionallity on a per-economy plugin basis. Should the extension not support EssX for whatever reason then it has to output `0.0` because there is simply no way of getting the baltop.

Of course, should Vault provide an API for obtaining that baltop it could be an Vault issue but sadly Vault doesn't support it - should really be something that is included though, but I doubt it will ever be added

**Comment by Geolykt** [comment]
Did you even enable baltop in the expansion? Also, it appears that Ess is treated specially: https://github.com/PlaceholderAPI/Vault-Expansion/blob/master/src/main/java/com/extendedclip/papi/expansion/vault/BalTopTask.java#L51 that would also cause this.

Consider creating an issue there: https://github.com/PlaceholderAPI/Vault-Expansion/issues/new they are the right authority for this

**Comment by Reese14** [comment]
"(!perms.hasPerm(player, "essentials.balancetop.exclude")" is referring to the permission 'essentials.balancetop.exclude', saying if a player has that permission that they will not show in /baltop. So if the player doesn't have that permission, they show on baltop, meaning %vault_eco_top_balance_#% should display them and their balance.

**Comment by Reese14** [comment]
I posted an issue on that github btw. In all honesty, I didn't know there was a separate github for the expansion itself, I was under the assumption that since it was a Vault placeholder that Vault handled it, but I guess not.
