### ISSUE TITLE
Support because DiscordSRV could not load

### ISSUE THREAD

**Issue by ErythroCraft** [MilkBowl/Vault#871]
Hi @MilkBowl

Got a problem with Vault and DiscordSRV.

Can you help or fix this?

Gere is the ERROR
https://pastebin.com/8gfswqVu

**Comment by Geolykt** [comment]
You may need to install a permissions plugins, but I am not too sure of how vault behaves without one installed so I can't say whether it is a user error, though I lean towards it

**Comment by cerealcable** [comment]
This appears to be a permissions issue and not a specific problem with Vault. Vault does not provide functionality on its own but is an abstraction layer for developers. If you have any issues please provide clear and reproducible information, ideally with a code example.
