### ISSUE TITLE
Nickname not displayed

### ISSUE THREAD

**Issue by Elric02** [MilkBowl/Vault#872]
Hello,

I have a weird issue since a few weeks : the in-game names (above players' head) aren't displayed anymore, and I can't figure out why. I didn't make any related change recently.
I'm coming here because I've tried deleting my plugins, and from what I've found there seems to be an issue with LuckPerms : nicknames aren't displayed anymore when LuckPerms and Vault are installed, but are displayed correctly if only one of them is installed.

Could someone help me please ? 

Thanks by advance

(note : running on latest build (b131), Paper 1.16.5)

**Comment by cerealcable** [comment]
Displaying or not displaying player nicknames is not a feature of Vault. Vault is an abstraction layer and is a tool to expand options for developers but this sounds like something beyond Vault. You've also described that with only Vault installed, the problem is not present.
