### ISSUE TITLE
Version 1.18.1 Error Vault is not up to date

### ISSUE THREAD

**Issue by F-TownGaming** [MilkBowl/Vault#873]
Version 1.18.1 Error Vault is not up to date!
[17:29:04 INFO]: [VentureChat] - Could not find Vault and/or a Vault compatible permissions plugin!

**Comment by Geolykt** [comment]
Do you have vault installed?

**Comment by cerealcable** [comment]
No information was presented in this issue. Closing this as there's nothing to act upon.

**Comment by F-TownGaming** [comment]
sorry that was my mistake now it works
