### ISSUE TITLE
1.18.1

### ISSUE THREAD

**Issue by jovan13343** [MilkBowl/Vault#874]
Can you please update to 1.18.1 coz in this state doesnt work

**Comment by cerealcable** [comment]
No information was presented in this issue. Closing this as there's nothing to act upon.

**Comment by ErythroCraft** [comment]
The information is updating the plugin to minecraft 1.18.x

**Comment by Geolykt** [comment]
Well, but the plugin should already work in 1.18+. What isn't present to why it does not work
