### ISSUE TITLE
[support for java 17]

### ISSUE THREAD

**Issue by javlock** [MilkBowl/Vault#879]
info:
```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12)
OpenJDK 64-Bit Server VM (build 17.0.1+12, mixed mode)
```
msg:`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project Vault: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.Processor (in unnamed module @0x3e8771a1) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x3e8771a1 -> [Help 1]`

**Comment by Geolykt** [comment]
This is interesting, however it should be noted that you can still use Vault on java 17 even if it does not compile on it.

**Comment by javlock** [comment]
yes, I understand this, I wrote about the error only when building the project

**Comment by Sleaker** [comment]
We don't build against java17, The plugin is byte-compatible with it at runtime so there's no reason for us to break compatibility with lower java versions just to make it compile at j17.
We also don't use lombok so I'm not sure where you're getting the above error from, but either way. no need to try and compile the project using jdk17.
