### ISSUE TITLE
Soft Dependancy

### ISSUE THREAD

**Issue by fahlur** [MilkBowl/Vault#881]
Is there any way to add soft dependancy to all the plugins this plugin includes, e.g. Essentials, Currency Core, DroxPerms, etc.?

[14:53:51] [Server thread/WARN]: [Vault] Loaded class com.earth2me.essentials.api.Economy from Essentials v2.19.3-dev+7-bb88a6a which is not a depend, softdepend or loadbefore of this plugin.

**Comment by boozaa** [comment]
In plugin's jar file for which the warning is thrown you can open the file 'plugin.yml' inside of it.
You can open a jar with 7zip or winrar for ewample.
Add a line inside this plugin.yml  
softDepend: [Vault]

**Comment by Sleaker** [comment]
@fahlur softdepends causes them to load in wrong orders, so no. Vault needs to load in startup so that it's classes are available for other plugins to load. The way it's setup is to allow for this registration to work in 2-steps.
