### ISSUE TITLE
Can you add Functions-Beta plugin economy and chat?

### ISSUE THREAD

**Issue by tianxiu2b2t** [MilkBowl/Vault#883]
Thanks authors

**Comment by Geolykt** [comment]
These days plugin authors have to hook into vault, vault doesn't support for other directly plugins now

**Comment by cerealcable** [comment]
Since Vault provides an API to attach economies (we no longer add support directly within Vault) this issue is being closed because its outside of our realm to implement.

**Comment by tianxiu2b2t** [comment]
> 由于 Vault 提供了一个 API 来附加经济（我们不再直接在 Vault 中添加支持），因此此问题正在关闭，因为它超出了我们的实施范围。
How I add API to Functions-Beta?
