### ISSUE TITLE
Is it stop update?

### ISSUE THREAD

**Issue by lijinhong11** [MilkBowl/Vault#884]
Is it stop update?

**Comment by Geolykt** [comment]
Why would vault need to get update (outside of a better API - but due to the nature of vault that is kinda hard to pull off)?

**Comment by Coosanta17** [comment]
apparently it doesn't work for 1.18.2 but it is seemingly working for me. I think it is the plugins connecting to vault that aren't properly updated

**Comment by Geolykt** [comment]
Vault continues to work as fine as it has the past years. I am not sure why there are so many people thinking otherwise but there has yet to be someone to come forward with concrete evidence outside of "it no work, pls update"

**Comment by lijinhong11** [comment]
> apparently it doesn't work for 1.18.2 but it is seemingly working for me. I think it is the plugins connecting to vault that aren't properly updated

Waht core are u using?

**Comment by lijinhong11** [comment]
> apparently it doesn't work for 1.18.2 but it is seemingly working for me. I think it is the plugins connecting to vault that aren't properly updated

And what economy plugin you using with Vault?
