### ISSUE TITLE
%vault_eco_balance_formatted% dont work

### ISSUE THREAD

**Issue by budur01** [MilkBowl/Vault#885]
https://prnt.sc/6FRAe0cp3ghc
https://prnt.sc/Pi5TjhQ7dS2h
https://prnt.sc/v9jSCzbn7UNX
and give error another plugin https://prnt.sc/v9jSCzbn7UNX
help me
ı cant use %vault_eco_balance_formatted%, expression is installed , essentials is installad, placeholderapi is installed

**Comment by Jack1424** [comment]
You need to go use the command `/papi ecloud download <expansion>` and replace <expansion> with the expansion that you want to use. You can find all of the expansions [here](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders).

For example, to use Vault (which looks like is what you want to do), run `/papi ecloud download Vault` on your server. You will need to run `/papi reload` or restart your server for changes to take effect.

**Comment by cerealcable** [comment]
@Jack1424 provided a solution, looks unlikely to be a Vault error, feel free to reopen with more information if you think this is a Vault bug.
