### ISSUE TITLE
All the plugins I use say that the Vault cannot be accessed.

### ISSUE THREAD

**Issue by murongyuanye** [MilkBowl/Vault#886]
All the plugins that I installed that require Vault as a pre-plugin are prompted to not be able to access Vault. But the server console shows that Vault is started.
Includes: QuickShop-5.1.0.7, Auto-Tune-0.13.0, Slimefun-v2022.05
I've tested versions 1.7.3 and 1.7.2 of Vault and both have this problem.
To be honest, I'm not very familiar with things like plugins (I used to use mods more in the past). I've tried looking for a solution online, but I can't find a relevant solution, so I'm asking here.

Minecraft version: 1.16.5
Server: Mohist-1.16.5-995
The log file is attached
[latest.log](https://github.com/MilkBowl/Vault/files/8790791/latest.log)
.

**Comment by Geolykt** [comment]
Hybrids are known to implement the bukkit API incorrectly, which may be at play here.

Either way, according to your log file there is no plugin complaining about vault missing.
Also, an economy integration WILL NOT BE PRESENT if you do not have an economy plugin

**Comment by murongyuanye** [comment]
Okay, I think I have found the problem. Thanks for your help.
