### ISSUE TITLE
Update to 1.19

### ISSUE THREAD

**Issue by thatmirc** [MilkBowl/Vault#887]
Hi! Posting this issue to track if plugin is still updated.

Update to 1.19

**Comment by thatmirc** [comment]
Its not updated on their spigot page.

Native Minecraft Version:
1.14
Tested Minecraft Versions:
1.13 1.14 1.15 1.16 1.17

https://www.spigotmc.org/resources/vault.34315/

**Comment by Geolykt** [comment]
It's https://github.com/MilkBowl/Vault/issues/876, https://github.com/MilkBowl/Vault/issues/874, https://github.com/MilkBowl/Vault/issues/874, https://github.com/MilkBowl/Vault/issues/873 and https://github.com/MilkBowl/Vault/issues/870 all over again huh

**Comment by Ghost5lay3r** [comment]
My server have a problem with Vault on 1.19. The console says Vault starts during start up, but no other plugin we have that use vault can detect that we have it installed. Displaying we should download Vault.

**Comment by gadget78** [comment]
i will just note this, for others coming here wondering why things may not work, and blaming it on Vault/1.19
you may need to check the placeholders Wiki, for the download pack .. 
so for example, issue `/papi ecloud download Vault` command to download the vault pack extensions... 
then `/papi reload` for that to take effect... 
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#vault

**Comment by Geolykt** [comment]
What exactly did they print out? Chances are that it is instead an issue with the economy not being present or something similar

**Comment by Ghost5lay3r** [comment]
Found the fix for us. Downloaded the Vault version made by ZRIPS and voila!

**Comment by candy999** [comment]
> Found the fix for us. Downloaded the Vault version made by ZRIPS and voila!
where can Download?

**Comment by cerealcable** [comment]
This doesn't appear to be a real issue for Vault.
