### ISSUE TITLE
Vault overwrites Tab Prefix

### ISSUE THREAD

**Issue by HauberOfficial** [MilkBowl/Vault#896]
(repost because I just realized that this **IS** the official Vault github page)

Alright so,

When I install Vault on my server, the rank prefix in the tablist gets overwritten and there is no way to fix this besides uninstalling Vault.
Is there anything I can do? As there isnt any comparable Vault alternative.

My server is running on Paper 1.12.2 version 1620

Screenshot:
![image](https://user-images.githubusercontent.com/75539848/182038756-20c37dee-a2d7-4a09-a4c2-fcd63e75cdea.png)

**Comment by Jack1424** [comment]
What plugins are you running on your server?

**Comment by HauberOfficial** [comment]
![image](https://user-images.githubusercontent.com/75539848/182041438-02750751-602a-42f9-9a4d-a38fc86bb0aa.png)
All of these.
Also APrefixSystem should normally be activated, but I got no idea why it was disabled.

**Comment by HauberOfficial** [comment]
Actually I took a closer look, apparently APrefixSystem is loaded, but it doesnt work for some reason.

**Comment by Jack1424** [comment]
One of these plugins (maybe TabList?) is making changes to your tab list. You either need to change the configuration file of the plugin changing the tab list or change the prefixes/suffixes themselves.

**Comment by Jack1424** [comment]
> Actually I took a closer look, apparently APrefixSystem is loaded, but it doesnt work for some reason.

Check the server log. It should have an error message that could indicate the problem.

If you can't fix it, LuckPerms has a list of plugins that they suggest for things like this. You can find it here: https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta#bukkitspigot

**Comment by HauberOfficial** [comment]
![image](https://user-images.githubusercontent.com/75539848/182085208-d2b68a8f-5411-4b6f-89c4-26d170c5ad4e.png)
Okay so apparently there is an error. But as I don't dev, I have no clue on what to do
Also, it isnt the Chatprefix, its the prefix shown in the Tablist

**Comment by Jack1424** [comment]
The third line in the screenshot says:
`Prefix '§5YouTuber §8| §5' is longer than the limit of 16 characters`

That prefix is 17 characters long. You can either shorten it or, if you can't shorten it, use another tab list/name tag plugin.

**Comment by HauberOfficial** [comment]
Ah I see. Lemme change that and see if that solves the problem

**Comment by HauberOfficial** [comment]
Okay, so it appears that it was more than just that rank. Which I have corrected now, however it still shows what I don't want
![image](https://user-images.githubusercontent.com/75539848/182092653-126d3660-aafe-4f11-b39c-096b06544cd2.png)

**Comment by HauberOfficial** [comment]
This time, there is no error I could find which is relating to the prefix system. So I have no idea why it still shows that

**Comment by Jack1424** [comment]
Can you send the configuration file for your tab list plugin?

**Comment by HauberOfficial** [comment]
I reinstalled the Tablist Plugin yesterday and haven't customized it yet so it still has the default config

`
# Placeholders formatting
placeholder-format:

  # TPS color format for %tps% placeholder.
  tps:

    # https://github.com/montlikadani/TabList/wiki/Ping-or-tps-formatting
    formats:
    - '&a%tps% > 18.0'
    - '&6%tps% == 16.0'
    - '&c%tps% < 16.0'
    enable: true

    # How many numbers do you want to display after "." in %tps% placeholder?
    # The number should be higher than 0.
    # Example: 3 = 19.14
    size: 2

  # Ping color format for %ping% placeholder.
  ping:

    # https://github.com/montlikadani/TabList/wiki/Ping-or-tps-formatting
    formats:
    - '&a%ping% <= 200'
    - '&6%ping% >= 200'
    - '&c%ping% > 500'
    enable: true

  # When the player changes the AFK status, change his tablist name format?
  afk-status:
    enable: false

    # Should the AFK format display in right or left side?
    # true - displays in right side
    # false - displays in left side
    show-in-right-or-left-side: true

    # Show player's group if the player is AFK?
    show-player-group: true

    # Format when the player is AFK.
    format-yes: '&7 [AFK]&r '

    # Format when the player is not AFK.
    format-no: ''

    # Sort AFK players to the bottom of the player list?
    sort-last: false
  time:

    # Time zones: https://www.mkyong.com/java/java-display-list-of-timezone-with-gmt/
    # Or google it: "what is my time zone"
    time-zone: GMT0

    # Use system default time zone instead of searching for that?
    use-system-zone: false

    # Formats/examples: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    # Format of %server-time% placeholder.
    time-format: mm:HH

    # Format of %date% placeholder.
    date-format: dd/MM/yyyy

  # Memory bar settings for %memory_bar% variable
  memory-bar:
    char: '|'
    size: 80
    colors:
      used: '&c'
      free: '&a'

      # When the server memory less than 80
      allocation: '&e'

      # When the server memory is on critical level (less than 40) and some resource need memory to run.
      released: '&6'

# Enable changing of prefix & suffix in player list?
change-prefix-suffix-in-tablist:

  # Disable groups in these worlds.
  disabled-worlds:
    list:
    - myWorldWithUpper

    # Use the list as whitelist?
    use-as-whitelist: false
  enable: true

  # Refresh interval in server ticks.
  # Set to 0 if you don't want to refresh the groups.
  # If 0, then you will need to execute the /tl reload command to refresh the groups.
  refresh-interval: 4

  # Automatically add groups from another plugins to the tablist groups.yml on every reload?
  # If a plugin does not support Vault, it will not be added.
  sync-plugins-groups-with-tablist: true

  # Hide player's group in player list when the player is vanished?
  # Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
  hide-group-when-player-vanished: false

  # Do you want to assign global group to normal groups?
  # true - "globalGroupPrefix + normalGroupPrefix"
  # false - "normalGroupPrefix"
  assign-global-group-to-normal: false

  # Prefer player's primary Vault group when assigning tablist group from groups.yml?
  # true - player will be assigned their primary vault group where possible
  # false - applies the group that has the higher priority in the permission plugin
  prefer-primary-vault-group: true

# Tablist objective types
# Shows your current health (with life indicator), your current ping or any NUMBER placeholder
# after the player's name (before the ping indicator).
tablist-object-type:

  # Objective settings
  object-settings:

    # The player's health - displayed after the player's name.
    health:

      # For these players the health will not be displayed
      restricted-players:
      - exampleplayer
      - players

    # Custom placeholder - accepts only number-ending placeholders, like %level%
    custom:
      value: '%level%'

  # In these worlds the objects will not be displayed
  disabled-worlds:
  - testingWorld

  # Types:
  # none - disables tablist objects
  # ping - player's ping
  # health - player's health
  # custom - custom placeholder
  type: ping

  # Interval for objects refreshing in seconds.
  refresh-interval: 3
hook:

  # Hook to PlaceholderAPI to use custom placeholders.
  placeholderapi: true

# Fake players that can be added to the player list.
fake-players:
  enabled: false

  # Do we count the added fake players to the %online-players% placeholder?
  count-fake-players-to-online-players: false

# If enabled, the gray color will not appear to other players when the player's game mode is spectator.
# The gray color will only show for the spectator player.
# Requires ProtocolLib!
remove-gray-color-from-tab-in-spectator: false

# true - does not count vanished players in %online-players% placeholder.
# Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
ignore-vanished-players-in-online-players: false

# true - count vanished staff in %staff-online% placeholder,
# but they need to have "tablist.onlinestaff" permission set.
# false - does not count vanished staff in the %staff-online% placeholder
# Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
count-vanished-staffs: true

# Hide player from player list when a player is AFK?
# Requires Essentials or CMI plugin!
hide-player-from-tab-when-afk: false

# Hide all players from the player list?
# This removes all players from the player list, but the player that has the
# group set is retained as it is not changed during removal, so your group
# will be restored if this option is disabled.
# Requires ProtocolLib to fix view distance issue! (https://github.com/montlikadani/TabList/issues/147)
hide-players-from-tablist: false

# Different player list in different world.
per-world-player-list:
  enabled: false

  # You can specify worlds, which will share the same list of players
  world-groups:

    # The key name, can be anything
    example1:
    - exampleWorld
    - exampleAnotherWorld
    exampleGroup2:
    - exampleWorld2
    - exampleAnotherWorld2

# Check for updates?
check-update: true

# Download new releases to "releases" folder?
# This only works if the "check-update" is true.
download-updates: false

# Log plugin messages to console?
logconsole: true
`

This is the tablist plugin I am using by the way, so it has multiple .yml files: https://www.spigotmc.org/resources/animated-tab-tablist.46229/

**Comment by HauberOfficial** [comment]
Also I just realized that it might be because of the Tablist Plugin, tho I am unsure

**Comment by Jack1424** [comment]
Make sure that you only have one plugin changing your tab list and configure it correctly. Also make sure that you have the correct prefixes and suffixes set and given to the correct users. You should be using color codes that work with your tab list plugin.

**Comment by HauberOfficial** [comment]
Yes, also found out that it was caused by the tablist plugin. So now I am searching for a alternative.

**Comment by Jack1424** [comment]
Check the LuckPerms wiki link that I sent. Those are all great plugins.

**Comment by HauberOfficial** [comment]
I found a good enough Tablist plugin which doesnt mess up the prefix so I'll close this now
