### ISSUE TITLE
Update the plugin plz to 1.18.2

### ISSUE THREAD

**Issue by kekev2001** [MilkBowl/Vault#903]
can you update the plugin update to 1.18.2 i need this for other plugins to commicate

**Comment by Jack1424** [comment]
Vault works on 1.18.2. What problem are you having?

**Comment by kekev2001** [comment]
i got [22:17:02 ERROR]: [ThemeParkHotel] Missing Vault! Please install it first. but it is in plugin list

**Comment by kekev2001** [comment]
![Uploading Schermafbeelding 2022-09-15 002237.png…]()

**Comment by kekev2001** [comment]
![Schermafbeelding 2022-09-15 002344](https://user-images.githubusercontent.com/56051728/190273551-e23c5126-e952-4797-b674-54f86a020845.png)
![Schermafbeelding 2022-09-15 002237](https://user-images.githubusercontent.com/56051728/190273465-cac8d9a6-8099-4fb4-8e95-6ac7dad7e2c1.png)

**Comment by Jack1424** [comment]
Run the `plugins` command and send a screenshot of the output

**Comment by kekev2001** [comment]
![Schermafbeelding 2022-09-15 002533](https://user-images.githubusercontent.com/56051728/190273745-9dab8f8a-0ed5-4c5a-9925-d0d27b060dad.png)

**Comment by Jack1424** [comment]
It looks like Vault is loading fine. Unless you see any errors from Vault in the log, this is probably an issue with another plugin and/or your server configuration/software.

**Comment by Geolykt** [comment]
If I had to guess an economy plugin is missing. Nothing wrong on the vault side of things

**Comment by cerealcable** [comment]
Given the error message is from ThemeParkPlus, why don't you reach out to them and they can tell you what their error message is meaning? Unfortunately given that we didn't generate the error there's not much for us to do here.
