### ISSUE TITLE
Economy Provider issue 

### ISSUE THREAD

**Issue by DaRacci** [MilkBowl/Vault#905]
Theres an issue with the provider system, It means that all economy plugins must specify that they should load before whatever plugin may be using the provider method when loading as this would provide the default abstract economy.
Is this just how it works or am i missing something here?

**Comment by Geolykt** [comment]
There is an implicit contract that economy providers must load as early as possible and employ all means to do so (initializing in clinit is a way to do it for example) and economy consumers must load as late as possible (use the service registration events!)

**Comment by DaRacci** [comment]
I suppose that makes sense, well guess it isn't an issue then really so ill be closing this.
