### ISSUE TITLE
Permission System Request (CloudNet -> CloudPerms)

### ISSUE THREAD

**Issue by alexander-rebello** [MilkBowl/Vault#908]
Hey, would it be possible to add CloudPerms, the standart permission system of CloudNet, to the list of plugins that Vault tries to load? ([Class](https://github.com/MilkBowl/Vault/blob/741a4929cdec43d5c95eca32272a5feed028df50/src/net/milkbowl/vault/Vault.java#L212)) [CloudNet](https://cloudnetservice.eu/) [Cloudnet Github](https://github.com/CloudNetService/CloudNet-v3)

**Comment by Geolykt** [comment]
Vault is the standard for such stuff, therefore it is up to the plugins to implement that standard.
The fact that Vault provides integration to a few plugins is a relic of an ancient past where vault was *not* the standard.

**Comment by alexander-rebello** [comment]
Okay, so in general no plugins are added to that list I assume. Still thanks
