### ISSUE TITLE
Please support database to optimize performance

### ISSUE THREAD

**Issue by ghost** [MilkBowl/Vault#913]
Please support database to optimize performance

**Comment by Geolykt** [comment]
Vault is not responsible for implementing the actual APIs provided by vault. Please ask the maintainer(s) of the implementing plugin(s) instead.

---
Also - I don't think database support is much of an optimization compared to a good flatfile implementation.

**Comment by ghost** [comment]
> Vault is not responsible for implementing the actual APIs provided by vault. Please ask the maintainer(s) of the implementing plugin(s) instead.
> 
> Also - I don't think database support is much of an optimization compared to a good flatfile implementation.

Thanks
